### ISSUE TITLE
Not matching available episodes

### ISSUE THREAD

**Issue by mrowlinson** [SickGear/SickGear#1040]
#### Branch version commit hash: e16f30a43fc3ef864217bfb8f604c47a60c142f3

I am having an issue with shows not matching available episodes at all or not matching the best quality available. I have all my shows set to download to a minimum of 720p Web-DL/BluRay. Most are set to 1080p. Some examples:

Blue Planet II - It would only match some 720 HDTV episodes available even though there were 1080p episodes in both Web-DL and BluRay available.
Drunk History - It didn't find any results even though there are 720 and 1080p Web-DL episodes available.
The Path - Show is a Hulu show so the minimum quality that can be available is 720p Web-DL. There are plenty of copies of both 720p and 1080p available. It won't match them.
The Chi - It matched a 1080p Web-DL result for the third episode but it missed episodes 1 and 2 even though there are plenty of matches for them in all desired qualities. 

If I look at the logs and manually view the feeds in an RSS reader it is showing episodes in desired qualities available so SickGear is seeing them but not matching them for some reason. Also, if I manually download and process them SickGear is matching them with the correct shows with no issue.

I've attached a full copy of my log so you can see where it ignored matches and also where I downloaded and processed them manually and they matches with no problem.

[**edit**] log removed thanks

**Comment by JackDandy** [comment]
Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

Thanks.

**Comment by mrowlinson** [comment]
What additional information are you looking for?

**Comment by JackDandy** [comment]
Please view the web page for this issue and not email as the post has been updated with what you asked and emails are not resent on post updates.

**Comment by mrowlinson** [comment]
Please view what webpage? The how to report issues? I did and I don't see what relevant information I'm missing.

**Comment by JackDandy** [comment]
STEP3.
An exact sequence of steps that can be taken to replicate the issue from a position of not having the show in a library, to adding the correct one, to selecting a particular episode and making it wanted or whatever you do that will trigger the error you reported, include your quality settings.

**Comment by mrowlinson** [comment]
You can trigger this issue any number of ways. You can do a backlog search, you can mark an episode as wanted. In the case of Blue Planet II I noticed the issue as soon as I added the show to my library this morning.

**Comment by JackDandy** [comment]
Ok you are not getting this, we already tried 40 mins ago, it works fine in tests, that is why i ask for specifc steps and relevant show configuration from you - time already wasted by not letting me know what I need to help you.

**Comment by mrowlinson** [comment]
I'm sorry, I'm trying my best here.

Here is a screenshot of the config for Blue Planet II. I use the same settings for 99% of my shows, and some of them work perfectly fine and always match my desired qualities as they become available.

https://imgur.com/DFE0hUH

**Comment by JackDandy** [comment]
> Blue Planet II - It would only match some 720 HDTV episodes available even though there were 1080p episodes in both Web-DL and BluRay available.

Correct. You have not understood the custom settings tips on the left hand side. In your words above, there is no init match, therefore, nothing can upgrade until there is. You see that there are only web-dls available, therefore, you need to add wel-dl to your initial quality list.

**Comment by mrowlinson** [comment]
If I'm interpreting those tips on the left wrong then they aren't very clear in my opinion. I read them as choose one initial quality and then choose all the upgrade qualities you would like download. If this is wrong then something else is broken. Like I said, I have these same settings used for 99% of my shows and the vast majority of them will download a copy of each of the selected upgrade qualities as they become available. Even for new shows I have added in the past, it would download one of my upgrade qualities if they were already available.

**Comment by JackDandy** [comment]
Actually, the way things "used" to work was not optimal, this became obvious across a few use cases.  So now SG properly follows those those rules laid out on the left  For example, people could not select to upgrade a show and not upgrade old eps at the **same time**, there are other cases that also involved making the entire logic covering different cases, better.  Therefore, given your existing selection, given you know what things mean today, you probably need to make the change I advised across your shows.

**Comment by JackDandy** [comment]
>  then they aren't very clear in my opinion.

Okay, so redesigned...

<a name=""><img src="https://vgy.me/UZqK8g.png"></a>

It's on the PR list, I'm guessing you know how to get at it, if not then that's IRC fodder - otherwise it will be merged soon anyway.

**Comment by mrowlinson** [comment]
I still think that looks convoluted and confusing. The way Sonarr does it is much more clear IMO.




<img width="839" alt="screen shot 2018-01-29 at 9 31 35 am" src="https://user-images.githubusercontent.com/1900970/35515999-998b500a-04d8-11e8-9f5a-5bfc481daf8d.png">

**Comment by JackDandy** [comment]
Hmm, Sonarr has a tick where SG has a search icon containing a plus, Sonarr is a vertical list, SG groups SD, HD, WEB-DL horizontally.  SG has more text tips. But meh, you don't like it, have you even tried to use it? I probably should not have put up a screenshot, as you sound like you are theorizing base on that rather that actually feeling the UI in action. Ah well, hours wasted.

**Comment by mrowlinson** [comment]
I guess I don't understand why there needs to be 2 separate lists where multiple different qualities can be selected in each list? It seems to me making a first list where you select all the qualities you want and then a second where you can only select 1, which is your cut off quality aka the highest quality you want downloaded, makes it the most clear.

**Comment by mrowlinson** [comment]
Reading that article from the wiki was how I came up with my original settings that you said were wrong.

If the initial list if the "cut off" why does it say in the text next to it that it's the first download "before optional upgrades"? That makes it sound like that list is the minimum quality you want to download and the upgrade list must be anything higher than the initial quality that you want downloaded.

I understand this all makes sense to you because you've been doing this for so long but if you need a wiki page to explain how to use the settings that Sonarr makes completely clear with two little tool tips then the settings are convoluted.

**Comment by JackDandy** [comment]
> Reading that article from the wiki was how I came up with my original settings that you said were wrong.

Given what you wanted to achieve, and what you reported as an issue, yes, it sounds like you did have your settings wrong, or that you didn't understand the effect of the settings (especially so given you may have been comparing SG with Sonarr's approach).  You didn't have webdl quality set in your "Initial" list, and expected webdl's to have snatched because they were selected in the "Upgrade to" list. However, the fact that the list is called "Upgrade to" implies that there needs to be something to upgrade to in the first place, and there was not.  

>If the initial list if the "cut off" why does it say in the text next to it that it's the first download "before optional upgrades"? 

It says this exactly due to your original post, to try make it clear for others that a quality select is made from the initial list and that the optional list is **optional**.

> That makes it sound like that list is the minimum quality you want to download and the upgrade list must be anything higher than the initial quality that you want downloaded.

Erm, not at all, not minimum quality, it clearly states "the best one found when searching will be snatched".  You download the quality that you initially want. And optionally, you can upgrade to one or more higher qualities,

> but if you need a wiki page to explain how to use the settings that Sonarr makes completely clear with two little tool tips then the settings are convoluted.

Having documentation does not at all mean that something is convoluted. User case scenarios that have been asked about over time have been added to that doc to save other users the time having to ask questions about what can be achieved, that's all.

If you can think of any wording change that will make things more clear, then that is very welcome.

**Comment by JackDandy** [comment]
I think this is the first issue to have both `invalid` and `enhancement` labels at the same time.

So, although the original point is indeed `invalid` because things are working as designed, the point that user confusion came from the UI provoked thoughts for `enhancement`.

After taking suggestions; the outcome is a removal from the UI of the multi-select boxes and wording such as "Initial".  The concept of a "Wanted quality" is now in effect alongside optional upgrades.  A button based system that offers help based on what is clicked has received positive feedback. The changes are now merged into all branches, are not a panacea, but do offer UX improvement.
