### ISSUE TITLE
Fail Trakt NOT authenticated

### ISSUE THREAD

**Issue by mixednutts** [SickGear/SickGear#1067]
#### Branch: The name of the branch (e.g. master or develop)

master

#### Branch version commit hash: (See the About page)

Expectation | Result
------------ | -------------
SickGear linked to Traktv Account | Error Fail Trakt NOT authenticated received

**Steps to reproduce:**
*1)* Open settings / notifications / social tab / enable traktv
*2)* Check that Add Account option is selected
*3)* Use link to get Traktv Pin (https://trakt.tv/pin/6314)
*3)* Log into Traktv and authorise SickGear to access Traktv
*4)* Copy PIN to SickGear TrakTV pin
*5)* Click Connect and error "Fail Trakt NOT authenticated" displayed
*6)* Confirmed application is not authorised via Traktv site

Log entry:

2018-03-03 16:35:41 ERROR    TORNADO :: Could not connect to Trakt. Code error: 401

Additional notes:
I confirmed with Traktv support that there are no restrictions on my account (VIP) that would prevent this authorisation.

**Comment by mixednutts** [comment]
Tried again with Develop branch with latest commit but same result.

**Comment by JackDandy** [comment]
Strange, when you copied and pasted your pin, did you make sure to remove any leading or trailing spaces that could have been introduced?

**Comment by mixednutts** [comment]
Yep - saw that happened when I first copied into it so double checked after that.

**Comment by JackDandy** [comment]
I have heard that the auth system was going to change, mine is already authed from way back so existing authed users are not affected, but a change would affect new auths like your case,  this will be investigated.

**Comment by JackDandy** [comment]
Feedback about this...

It looks like Trakt broke the old auth method .... their official position for the auth pin system is ... '**it will still continue to work indefinitely**' .... but user reports on other apps show that people get a 401 error
and since the page is still there and you get a code, they must have broken the API.

Basically, the server returns a 401 error, which is non-sense since you are requesting an auth code.

We are not sure if Trakt will fix this issue, and fear they will pass it back to all app developers to recode their auth systems. "Indefinitely" does not mean what it is supposed to in the dictionary according to Trakt. Worse, "their new method is really sh**ty for apps like this, as in a lot of work and code to integrate" - so for just an auth system, this is not good. 

Sorry, but expect this to take time to resolve.

I will close this issue now as it is a somewhat muted "enhancement" and therefore, added to our todo.

**Comment by JackDandy** [comment]
Hello again, 
Some loose ends need to be resolved, and the UI needs to change to fit, but we do have something working.  A good enough time as any to put this early callout and have you ready.  If you can idle in the IRC channel, then I will be able to give you a message when we are ready for you to test. It's fine if not possible, I'm simply making the offer so that you can communicate any adjustments as rapidly as possible from an active IRC position rather than this thread.

**Comment by mixednutts** [comment]
Hey @JackDandy - not sure what has changed but I was able to connect the traktv account successfully just now.

**Comment by JackDandy** [comment]
Hi @mixednutts 

Yeah, seems they answered the reports and fixed it - great.

Given how much we have invested into the newer auth system - we may as well complete that.

Thanks for reporting back and letting us know :)
