### ISSUE TITLE
How do i remove a show from the favorites list?

### ISSUE THREAD

**Issue by tpitman** [SickGear/SickGear#1079]
#### Branch version commit hash: (See the About page)

Expectation | Result
------------ | -------------
Your expectation paragraph(s) text here. Before the bar >> | then, your result paragraph(s) text here.

**Steps to reproduce:**
*1)* Step to take
*2)* Step to take
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
nothing above is filled in, so i have no idea what this means, sorry.

**Comment by JackDandy** [comment]
@tpitman you keep coming into the IRC to ask questions, which is great, but we cannot support you at what is 4:30 am for us (GMT) - please try at a more appropriate hour. Thanks.

**Comment by tpitman** [comment]
What time  zone and time  would you most likely be able to be around?

**Comment by JackDandy** [comment]
the time you posted that q was most reasonable for a GMT + 0 tz ;)

**Comment by tpitman** [comment]
I understand that the time I posted was not good for you.

The question I have is when would be a good time for you? When are you
usually around and able to answer questions?

**Comment by JackDandy** [comment]
ok, you misunderstood me, i meant 3 hours ago was reasonable, as is also now.

**Comment by JackDandy** [comment]
@tpitman come back, i had to kick the handle because you pasted a log into irc - thats seriously frowned on as spam, that is what GitHub gists are for, lol

**Comment by tpitman** [comment]
Hey, this is Tony who did irc with you the other day about eps going back
to wanted. It just happened to all 24 of the shows I have. Before I created
an issue I wanted to email you and see if you want me to do that or just
send you the log.

Basically here is what the steps were:

1. notice all shows have several episodes that are wanted that I had
previously set to skipped.
2. notice that the eps changed to wanted are all after the episode that was
last viewed when I added the show to sg.
3. manually go through all the shows and set the wanted eps to skipped again
4. the next day I needed to reboot the computer, so I did.
5. after about 2 hours I noticed that all 24 shows now have those same eps
showing as wanted.

I created a gist with the log. Here is the url if that will help:

https://gist.github.com/tpitman/034a8cf8983b898ab3432c413a90de40

**Comment by JackDandy** [comment]
please come to irc

**Comment by JackDandy** [comment]
Youve posted 5000 lines of text there, i hope you don't think i have time to read through that. Why not disable all but one provider? takes steps to help isolate the issue instead of walking face first into a wall? There is nothing in that log about a backlog search (which there would be if items were "wanted") therefore, of those 5000 lines, not one is useful. You dont help by pointing out a line of the show that is supposedly wanted in the log that is - for example - being searched for. All there is, is a load of recent searches, which have nothing to do with what your complaint is. As you keep running away from irc, this issue is frustrated as you are not keeping close to us in order that we can deal with things quicker than once every few days, which is also a ballache. I did say, stick around the other day, and poof! you disconnected again. I dunno. But doing this over email is like using the postal service to me.

**Comment by tpitman** [comment]
I don't leave my computer  up and on all the time. It is a laptop that i
take to work each day, so i also pack it up and put it in my backpack, so
leaving irc up all the time would not work.

This way of doing this is different to me. I am used to sending information
back and forth via email.

I am starting to see how you like to do it.

As far as the log goes again your way is different is all. I am not sure
which lines mean something to you and which don't.

Let me know what would be most helpful and i will try to provide it.

**Comment by JackDandy** [comment]
I appreciate what you're saying. Okay, this is an issue tracker website where you will see that most issues are dealt with in under 5 posts in this project. However, corresponding on GitHub is non-productive for this type of case. You can get an account on one of many free IRC bouncer services so that you can re-connect to that and it will give you irc text missed while you were disconnected - BNC's are there to solve exactly your type of use case.

**Comment by JackDandy** [comment]
I appreciate what you're saying. Okay, this is an issue tracker website where you will see that most issues are dealt with in under 5 posts in this project. However, corresponding on GitHub is non-productive for this type of case. You can get an account on one of many free IRC bouncer services so that you can re-connect to that and it will give you irc text missed while you were disconnected - BNC's are there to solve exactly your type of use case. (maybe https://znc.bg)

**Comment by JackDandy** [comment]
Can you confirm if the files that download again are **only** of type repack/propers ? (if yes, you can prevent this happening for now by disabling PROPERS in config/search)

**Comment by tpitman** [comment]
I will take a look when I get home.

**Comment by tpitman** [comment]
As far as I can tell they are not PROPERS. They are just eps that I have
already watched that are now wanted.

I am going to turn off that option, though.

**Comment by JackDandy** [comment]
bah, ok, well when you can sort out your irc properly then we can continue a proper back and forth dialog.
