### ISSUE TITLE
Feature Request: onTxComplete.bat Hardlink

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#1095]
Since nzbtomedia function stopped working with the new security update I switched to the .bat @JackDandy made last time I had issues with nzbtomedia I decided to switch to the .bat file, a bit more I/O on my disks but other then that it works great.
It was a bit of a pain to set up since uTorrent 2.2.1 didn't pass "SG" or the file paths correctly (fixed with `cmd /c start "" /B <path>\autoProcessTV\onTxComplete.bat "<Path to files>\Process" "tv" "tv" "%D\%F"` manually replacing both labels and file paths) but it works great, unfortunately more I/O then nzbToMedia because it rotates a scan every x minutes causing a spinup but minor issue, bigger issue is that it's a copy function only.
 
So my request, is it possible to add a mklink toggle in this kind of way `cmd /c mklink /h "<path to files>\process\*" "<path to files>\download\*"` that's what I've been using for years now and always seems to have done the trick but not possible because the copy function is completely integrated in the .bat.

**Comment by JackDandy** [comment]
> because it rotates a scan every x minutes

Sounds like you have not disabled the setting "Scan and post process" in Post Processing.

**Comment by JackDandy** [comment]
Yes, this is by design. Making a link will also spin up a drive - perhaps for less time, but meh. 

Anyway, if you would like to improve the batch ...

then you could add a param to make a link instead of doing a file copy.

That would be an interesting contribution that others may also appreciate.

**Comment by Th3MadHatter** [comment]
`Sorry, but NO! Hardcoding labels sends every file type completed to be processed - so you increase i/o usage and break what the script was actually designed to do. Labels do work, use uT v2.2.1 (or replace uT with qT) with the set up as instructed and you will see it works as designed. There is a dev flag in the script you can use to test - it simply outputs to console what would be sent to SG instead of actually sending.`

Usually I'd agree with you but running it in test mode it didn't do anything, it was the issue I had when you first created it and the issue persisted so I just moved back to NzbToMedia but since that's no longer an option I had to dive in and tweak it.
Setting F:\sg_pp was the biggest problem because my F:drive letter is in use and unapproachable (no r/w/rw/anything) so changing that solved that. I labeled the "tv" "tv" labels because first they both showed up empty in test mode, hardcoding them picked up the label. 

It might increase CPU usage a bit but it works, that was not the I/O I was though.
NzbToMedia gets triggered on event "complete", symlink/junction/copy to PP directory and then triggers the PP event in SG (or it used to) causing a spin-up when REQUIRED.
The .bat gets triggered on event "complete", copy to PP directory and then ends.
SG then triggers a directory scan for the PP process causing a spin-up every x minutes.
In the long run that puts more lifting on a drive, it's minimal but the head does have to move every x minutes even if no PP is required.
That's the I/O I was talking about.

> what you cannot do is change cmd /c start ... to cmd /c mklink
I know, the .bat has to be triggered the way it is, it could call a secondary window frow within the already running screen but that's not really required I think, or maybe it is, I don't know yet.

> 
> instead, you could add an optional param5 to onTxComplete.bat which could be used to make a link instead of the default file copy action.
> 
> Your uT setup could then be ...
> cmd /c start "" /B [script dir]\onTxComplete.bat "F:\sg_pp" "SG" "%L" "%D\%F" "link"
> where param5 = "link".
> Then, in onTxComplete.bat, add... if param5 eq 'link' then do make link else do default copy.
> 
> That would be an interesting contribution that others may also appreciate.
> 
> I will leave this as an exercise for you.

I'm going to give it a try, I unfortunately have very little time on my hands at the moment (hence me requesting instead of sending a push request :stuck_out_tongue: ) but when I do find some free time I will certainly look at it. 
I assume a lot of users would appreciate it because a lot of people mklink either sym or hard because it's easy to manage and if a file is 1GB it doesn't use 2GB for no real reason unless you WANT it to be copied.
I don't know if I'll succeed in it, I checked the code and am completely unfamiliar with it (even though you did describe every aspect) but I can give it a shot (you most likely write it in 5 minutes and I in 5 weeks, if I get it to work at all, but that's the way the cookie crumbles).

**Comment by JackDandy** [comment]
Actually, the COPY is the best common ground for all users that there is. 

A hardlink to the seeding file means that if the seeding file is accidentally deleted, then it is gone from SG and from your media player - this means having to think about every file deletion and adds an additional thought task (read:burden).  Also, a hard linked file cannot be deleted from inside SG becuase that will break the client seeding process. This then affects things like the ability to use the SG watched state feature without being compromised. Yes, you can use sym links instead of hard links, and then there are issues where OSs don't permit cross drive links, then perms, then... then... then... Nope, copying is the lesser complex for *most* users. 

These are not the ONLY reasons why linking is actually not a good idea in practice. I have more but there's no point banging on and on. Suffice to say, if you torrent, then it is very good practice to copy your seeding file in order to decouple the SG copy from the download client copy. Two copies are in play for as long as you keep the downloader client copy, once seeding is done, that copy is deleted and you are left with the master SG copy. If you want to seed forever, then drive capacities are very cheap at 5400rpms that is way suitable for torrent and media playback use + they keep cool and have longer lifespan as they revolve slower. Anyway, all of this is academic, you have suggestions, enjoy.

**Comment by Th3MadHatter** [comment]
I know how junctions work exactly, I can't afford doubling the capacity of my current drives, I link, I know 1000's of others that link files, not in SG alone but in general for the very sole reason that IT SAVES SPACE (among other things). 
If your data is really important and afraid of data corruption? No problem, you have highly compressed backups for that, meaning instead of copying 500 files of 1GB ending up with 1TB of data you have 500GB of files and maybe 250GB of backup (depending on the compression rate etc.)
Not afraid of that? or rather have 250GB spare AND have a backup? Link.
That's a big part of why the idea was invented.
That said, you don't want to do it because you don't use it, you can buy and house (including electricity cost) 5 extra 5TB disks whenever you feel like it so you don't feel like writing it or making it compatible with NzbToMedia again.
'Nuff said, start with "I don't feel like writing 10 lines in my script because I won't use it" don't give me a lecture on how it works or on how you would do it because I've been using SB/SR/SG for about as long as you do and I know how a copy function works (and you know I do).

I ask for support I get none but a lecture, that doesn't help me nor anyone else that Links.

I looked into the code, says absolutely nothing to me, but then again I don't ask you to finish my work you know nothing about either, so I'm going to ask others for advice and else just migrate.
I'm not asking for impossible or rare things, I'm asking for something that would actually help a great amount of users.
But kudos Jack, you used to be friendly and helpful back when you played second fiddle to Ech, seems like thats just totally gone and the same amount of helpfulness passed on when you evolved with your own branch. :1st_place_medal: 

Thanks for absolutely nothing, have a great day.

**Comment by JackDandy** [comment]
> I know how junctions work exactly......

Yes, and many, many, more **Windows** readers of this thread do *not* know even of the existence of junction points because they are not near as ubiquitous as on Linux. Therefore, balancing that part of the answer so that other readers could appreciate that conversation is where I came from. Of course *you* know about links, but this feature was made for the most common use case, as is already explained.

> making it compatible with NzbToMedia again

Wait, if a tracker changes their site, or TVDB API changes, we don't ask them to make SG compatible with their site again.  I don't write NzbToMedia, but it was directly calling SG functions in a way that when the security of SG was improved it simply no longer worked,  SG can't forsake improving its security for an external tool - it is the prerogative of the author if he wishes to support change, and we could for example, add an official API endpoint for it.

> start with "I don't feel like writing 10 lines in my script because I won't use it" or just "No"

As a courtesy, I felt that you deserved more than just a "No" so I gave my time to explain about why decisions have been made. I also said (in the previous post) what to look for in the completely self-contained batch file that is not Python code, just good old, well documented DOS commands.

**Comment by JackDandy** [comment]
> I know how junctions work exactly......

Yes, and many, many, more **Windows** readers of this thread do *not* know even of the existence of junction points because they are not near as ubiquitous as on Linux. Therefore, balancing that part of the answer so that other readers could appreciate that conversation is where I came from. Of course *you* know about links, but this feature was made for the most common use case, as is already explained.

> making it compatible with NzbToMedia again

Wait, what?! If a site changes, or TVDB API changes, we don't ask them to make their site SG compatible again.  I don't write NzbToMedia and unfortunately, it was directly calling SG functions in such a way that the improved SG security prevented that insecure use.  Naturally, SG cannot forsake improving its security; it's up to authors if they wish to support our changes, we can for example, add official API endpoints for third party use, these are stable, secure and the way external app should connect to SG instead of what was being done.

> start with "I don't feel like writing 10 lines in my script because I won't use it" or just "No"

As a courtesy, I felt that you deserved more than just a "No" so I gave my time to share some of the rationale behind the decisions. I also said (in the previous post) what to look for in the completely self-contained batch file that is not Python code, but just good old, well documented DOS commands.

**Comment by JackDandy** [comment]
> I know how junctions work exactly......

Yes, and many, many, more **Windows** readers of this thread do *not* know even of the existence of junction points because they are not nearly as ubiquitous as on Linux. Therefore, balancing that part of the answer so that other readers could appreciate that conversation is where I came from. Of course *you* know about links, but this feature was made for the most common use case, as is already explained.

> making it compatible with NzbToMedia again

Wait, what?! If a site changes, or TVDB API changes, we don't ask them to make their site SG compatible again.  I don't write NzbToMedia and unfortunately, it was directly calling SG functions in such a way that the improved SG security prevented that insecure use.  Naturally, SG cannot forsake improving its security; it's up to authors if they wish to support our changes, we can for example, add official API endpoints for third party use, these are stable, secure and the way external app should connect to SG instead of what was being done.

> start with "I don't feel like writing 10 lines in my script because I won't use it" or just "No"

As a courtesy, I felt that you deserved more than just a "No" so I gave my time to share some of the rationale behind the decisions. I also said (in the previous post) what to look for in the completely self-contained batch file that is not Python code, but just good old, well documented DOS commands.

**Comment by JackDandy** [comment]
> I tried asking the guy at SG to add a linking option to his batch script (which only copies) 

yes

>but he doesn't feel like it and suggests everyone to just buy extra HDD's and do it his way...

This is an straight lie because the first reply on this thread gave help on how and where to add linking.

**Comment by JackDandy** [comment]
> I tried asking the guy at SG to add a linking option to his batch script (which only copies) 

yes

>but he doesn't feel like it and suggests everyone to just buy extra HDD's and do it his way...

This is an straight lie because the first reply on this thread gave help on how and where to add linking. Your attitude is self-entitled with an unpleasant tone. I did have this set for future dev; of something I don't use but to give my time for you, and now, forget it.

**Comment by JackDandy** [comment]
> I tried asking the guy at SG to add a linking option to his batch script (which only copies) 

yes

>but he doesn't feel like it and suggests everyone to just buy extra HDD's and do it his way...

This is a straight lie because the first reply on this thread gave help on how and where to add linking. Your attitude is self-entitled with an unpleasant tone. I did have this set for future dev; of something I don't use but to give my time for you, and now, forget it.
