### ISSUE TITLE
Post Processing and third party scripts

### ISSUE THREAD

**Issue by JackDandy** [SickGear/SickGear#1099]
Hi @clinton-hall

Could you change the case of `sickgear` to `SickGear` 
[at this line](https://github.com/clinton-hall/nzbToMedia/blob/ee243fbba51e66ed12ad17d57e016b4db5bdc720/core/__init__.py#L67)

Thanks for your consideration.
JD

p.s. I have "closed" this issue so as to not have it in the main "open issues" view ;-)

**Comment by clinton-hall** [comment]
Hopefully this cleans it up... a lot of historical handling here and I had to get my head around how it was used.

I used a simple (dirty) replacement so that anyone who has manually set the fork in the config with all lower-case should continue to have this function, but log the Case-Sensitive name...

I also added the login changes to the auto-fork detection, so in theory this should allow the script to recognize the difference between SickGear and other SickBeard forks without the user having to specify.

**Comment by JackDandy** [comment]
Brilliant, thanks @clinton-hall :)
