### ISSUE TITLE
Error adding show

### ISSUE THREAD

**Issue by triney37** [SickGear/SickGear#1109]
#### Branch version commit hash: (See the About page)

Expected to be able to add a show without error.

Currently when I add a show I receive this error. When I add a custom whitelist group.
Error
Not sending, banned

**[edit] tracelog removed, not reqd. thanks**

**Comment by JackDandy** [comment]
> Not sending, banned

Sounds like you have your set up too aggressive for abda, it has tight access thresholds.
 
To manage this will require some manual effort from you to bring things back in line...
First, disable all your anime shows.
Then enable only one show and most inportantly make sure there is no wanted episodes on it apart from one at the most - this is so that you will at leat see some feedback from abda. 
Periodically check the logs for abda to unban you.

Good luck.

**Comment by triney37** [comment]
What if I just disabled ADB?

**Comment by triney37** [comment]
ok thanks for helping me out!

**Comment by JackDandy** [comment]
Title changed because the "Error adding show" is misleading. 

The ban error message **does not prevent** the show from being added. A show is added even if an account is banned, it is simply added without an item selected from white/black list - although manual entries for either can be easily added anyway.
