### ISSUE TITLE
QQ: delete episodes during postproc not working as expected

### ISSUE THREAD

**Issue by mgaulton** [SickGear/SickGear#1113]
Hi There, 
I don't know if this is an actual issue or a configuration issue.
The expected behaviour is that when PP is performed, if an episode is not used to replace due to unwanted quality, wanted quality already present or smaller/same size as existing file, that the PP would delete those episodes. I'm finding that isn't the case, so I have a big folder of stuff not cleaned up.
Am I doing something wrong?

**Comment by JackDandy** [comment]
Nope you are not. Consider it the other way around, how people would be very annoyed if files where deleted because they did not meet some requirement. It is for this reason that file management at this level is your responsibility. Note, this situation does not presents when SG is doing the searching becuase, it knows not to snatch stuff that are not wanted - another reason why you are outside the scope of normal operations with this one.
