### ISSUE TITLE
Encountering error on processing any media

### ISSUE THREAD

**Issue by RandomTask83** [SickGear/SickGear#1115]
#### Branch version commit hash: baf5f9b008be911c8bc7e28e0460b436c14e0247

Expectation | Result
------------ | -------------
Post-process media | Presented with a script error screen stating 'list' object has no attribute 'split' 

**Steps to reproduce:**
*1)* Manually process media or run script via SABnzbd

...

https://gist.github.com/RandomTask83/a73269782bd9cb8abf0c5d7293792b4f

Additional notes:
I'm seeing references to "tautulli_token_..." in the Request Info portion and am wondering if that may have something to do with why I'm encountering this error.  Can I not have Tautulli running at the same time as SickGear?  Everything had been running just fine until a few days ago.

**Comment by JackDandy** [comment]
The issue is something to do with the metadata for that particular show and a bug where data is not as expected. This will be looked into and fixed.

1) Go to config/Post Processing/Metadata
2) Select drop down Metadata target/MediaBrowser
3) Uncheck all items on there
4) Save Changes

If you still use MediaBrowser you can do the opposite after you have processed the data.

**Comment by JackDandy** [comment]
[Fixed](https://github.com/SickGear/SickGear/releases/tag/release_0.16.22)
