### ISSUE TITLE
New Girl failed to parse

### ISSUE THREAD

**Issue by Merwenus** [SickGear/SickGear#1121]
#### Branch version COMMIT: 790e4e24e99f87b6cb848eb94677e2cbca9846a9

Expectation | Result
Parse New Girl TV show from download folder to series folder | Nothing 
Your expectation paragraph(s) text here. Before the bar >> | then, your result paragraph(s) text here.

**Steps to reproduce:**
*1)* Download and rename automatically with Flexget to this: 
New Girl - s06e15 - Glue.mkv
*2)* Wait for parse, failed.
...

https://pastebin.com/HrJhExfP

**Comment by TwilightIT** [comment]
Install Sonarr, Problem Solved!

**Comment by Merwenus** [comment]
Sonarr is not really working in Hungary, there are no good sites for hungarian serieses. etc.
We have specific hungarian torrent sites, thats why I stuck at Flexget+Transmission.
And I used SickBeard for years without an issue, but wanted to try something new like SickGear, but it miss a few things, and thougt I report to help the issue of my fellow hungarians in the future.

**Comment by JackDandy** [comment]
Looking at that log file, 
```Must add show to SickGear before trying to post process an episode```
If the show is already added, then there is no quality tags in that filename, therefore make sure to set the show quality to unknown.

**Comment by JackDandy** [comment]
Set show quality to "Any". That file has no quality strings, therefore, sg wont process it. This assumes that you do actuall have the show in your SickGear library.

**Comment by JackDandy** [comment]
Assuming that you do indeed have the show "New Girl" in your SickGear library, set its show quality to "Any" -- the filename you posted has no quality strings, therefore, SG wont process it unless quality is set to "Any". 

Also, if you are using RSS to download via FlexGet, then consider adding that RSS feed into SG directly, that way, you won't need to use "ANY" (which is a _catch all_ for the above case) and will instead be able to specify quality like HD so that SG can target the quality better, therefore, you will gain from the facilities that the SG search system has.

**Comment by JackDandy** [comment]
Assuming that you do indeed have the show "New Girl" in your SickGear library, then set its show quality to "SD" (or use custom, enable "SD") -- the filename you posted has no quality strings, and SG won't process/find a file named without a quality unless you include "SD" in a shows qualities. 

Also, if you are using RSS to download via FlexGet, then consider adding that RSS feed into SG directly, that way, you will be able to specify quality like HD or SD and SG will target on the quality, therefore, you will gain from the facilities that the SG search system has and not have the above issue at all.
