### ISSUE TITLE
Unable to send torrents to Download Station on DSM6

### ISSUE THREAD

**Issue by bxlouis** [SickGear/SickGear#1122]
#### Branch version commit hash: 790e4e24e99f87b6cb848eb94677e2cbca9846a9

Expectation | Result
Being able to download torrents using Download Station on DSM 6. | Unable to send Torrent to DS. Return code undefined.

**Steps to reproduce:**
*1)* Settings -> Search -> Torrent Results -> Select Synology DS
*2)* Configure DS and test the connection : "Success: Connected and Authenticated"
*3)* Add a new show and force a backlog search
*4)* Check log file "Warning and the next level"

<pre>
2018-08-27 20:23:23 WARNING  POSTPROCESSER :: Failed! Did not process any files. (...2 repeat lines)
2018-08-27 20:15:22 ERROR    BACKLOG-331600 :: DownloadStation: Unable to send Torrent: Return code undefined (already exists in client?) (...7 repeat lines)
2018-08-27 19:51:26 WARNING  POSTPROCESSER :: Failed! Did not process any files. (...4 repeat lines)
2018-08-27 19:46:22 ERROR    BACKLOG-331600 :: DownloadStation: Unable to send Torrent: Return code undefined (already exists in client?) (...7 repeat lines)
</pre>

Additional notes:
DSM version: DSM 6.2-23739 Update 2
Works very well with Transmission: Same settings
Permissions are R/W for both DownloadStation and sc-sickbeard-custom local users on the Downloads folder.

**Comment by JackDandy** [comment]
Please come to IRC where I can look at running tests with you about this, otherwise, there is nothing i can do apart from leave this logged as an issue until someone else can.

**Comment by JackDandy** [comment]
No response from user, marking invalid.

**Comment by Wee-bear** [comment]
I am having the same problem.  I thought it might be the fact that I was using https:  and port 5003  but I switched to http:  and port 5000 as the default suggest and the results are the same.
The test says 'Connected and Authenticated'   but still returns 
2019-02-05 16:27:28 BACKLOG-104281 :: DownloadStation: Unable to send Torrent: Return code undefined (already exists in client?)
![screenshot from 2019-02-05 16-57-33](https://user-images.githubusercontent.com/47355751/52285835-61c23a80-2967-11e9-93f0-b4e023dd588a.png)

**Comment by Wee-bear** [comment]
Black hole works but the Synology DS link doesn't   I have checked the permissions and they are set properly.
![screenshot from 2019-02-05 17-01-30](https://user-images.githubusercontent.com/47355751/52286062-cf6e6680-2967-11e9-90ca-5c2a1d69fde6.png)

**Comment by JackDandy** [comment]
Perhaps it's time to remove this DS option unless someone can help with the code given that without a docker image so that I can run a simulated development system to test this out, then there is nothing i can do as I don't have this HW.

**Comment by JackDandy** [comment]
Perhaps it's time to remove this DS option unless someone can help with the code given that without a docker image so that I can run a simulated development system to test this out, then there is nothing i can do as I don't have this HW. Also, both the blackhole method, and using a different client (i.e. Transmission) are fine on DS anyway. If only there was a docker, I could just build enough energy to give this a look, but alas.

**Comment by Wee-bear** [comment]
I would be willing to help if you could walk me through it.  I could give you maybe remote access or you can tell me how to get the info you want.
Any chance you can get the code from the SickRage project on Git?  I worked well for me.
You are right that the black hole method works so...

**Comment by JackDandy** [comment]
hmm, okay then, if you come to IRC and private chat me, we can look at possibilities

**Comment by Wee-bear** [comment]
Ok. how do I get there?

**Comment by Wee-bear** [comment]
I'm new on here

**Comment by JackDandy** [comment]
irc.freenode.net channel #SickGear

**Comment by Wee-bear** [comment]
registring

**Comment by JackDandy** [comment]
After changing code, and performing tests with new code, I could not replicate the issue, the code had not changed that much so I rolled back to the existing code and retested, still no issue. Unfortunately, the test server is now gone so I have to wait for user to come back. But my conclusion is that the error reported is correct and that people want to ignore the error instead of using the DS filter feature to find the item that really does actually exist, I will put something in the Syno install wiki page about this.

**Comment by JackDandy** [comment]
Addressed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.18.12)
