### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by esp123** [SickGear/SickGear#1123]
BRANCH: master / COMMIT: 790e4e24e99f87b6cb848eb94677e2cbca9846a9

--

Expectation | Result
------------ | -------------
while running in the background, it crashes for unknown reason | see logs

**Steps to reproduce:**
*1)* N/A - not being used, running in the background.
 ..

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags
[console.txt](https://github.com/SickGear/SickGear/files/2327155/console.txt)
[sickgear.log](https://github.com/SickGear/SickGear/files/2327156/sickgear.log)
[console2.txt](https://github.com/SickGear/SickGear/files/2327157/console2.txt)

Additional notes:
see logs

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
The steps section requested when this issue was created, enables your reported issue to be replicated and investigated, however,  there is no idea how to trigger your reported event in order to fix it for you. Until you can supply this information, then there is no choice but to mark this issue "invalid" as what you are reporting cannot be verified. Sorry.

Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

There's no need to open a new issue, additions to the end of this thread are just fine.

Thanks.

**Comment by JackDandy** [comment]
Install lxml using pip.

**Comment by JackDandy** [comment]
> it crashes for unknown reason

The reason is shown in the first line after you run SickGear - in your file `console.txt`...

`/opt/SickGear/lib/imdb/parser/http/utils.py:482: UserWarning: unable to use "lxml": No module named lxml.html`

The third party library `imdb` requires that you install **lxml** using pip (python cmd).

We are aware of this and are already taking steps to replace the third party library, but in the meantime, you can simply install `lxml` yourself, something like this ...

`python -m install lxml`

should be fine.

**Comment by JackDandy** [comment]
[Release 0.17.1](https://github.com/SickGear/SickGear/releases/tag/release_0.17.1) carries changes for all issues raised in the logs of this issue.

Thanks for your feedback.

**Comment by JackDandy** [comment]
[Release 0.17.1](https://github.com/SickGear/SickGear/releases/tag/release_0.17.1) carries changes for all issues raised in the logs of this thread. Installing `lxml` is great for improving parsing performance over not having it installed, however, SG is able to run without it again. 

Thanks for your feedback.
