### ISSUE TITLE
New feature - Add manual search to episode status management

### ISSUE THREAD

**Issue by mrburton03** [SickGear/SickGear#1136]
Feature request:

On the episode status management page add a manual search button next to the episodes that show up as wanted once expanded.

**Comment by pokerface3** [comment]
That's not a fix. I've been pressing the magnify glass and opening it to a new tab for it to search but this use to work until recently.

**Comment by JackDandy** [comment]
> That's not a fix.

Correct, because there is nothing broken to fix.  

> ... this use to work until recently.

Nope, SickGear has _never_ had a magnify glass on its **episode status management** page so it seems you are confusing things.  Anyway, following the steps described above will trigger a background search on selected episodes.

Feel free to ask anything else below, even though it is closed that's no problem.
