### ISSUE TITLE
Wiki Install Instructions Incomplete

### ISSUE THREAD

**Issue by esp123** [SickGear/SickGear#1152]
Error when following: https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B3%5D-Ubuntu

pi@P:~ $ python -V
Python 2.7.13
pi@P:~ $ sudo snap install sickgear
sickgear 0.18.9 from 'sickgear' installed
pi@P:~ $ sickgear
**bash: sickgear: command not found**
pi@P:~ $ sudo nano /etc/init/SickGear.conf
pi@P:~ $ sudo nano /etc/default/sickgear
pi@P:~ $ sudo service SickGear start
**Failed to start SickGear.service: Unit SickGear.service not found.**

Missing SickGear.service file or instructions on how to set one up. Can the instructions on the Wiki please be updated and tested.

**Comment by JackDandy** [comment]
The `service` is not required when running with snap, the most hard work of getting snap working is complete and you can use the normal snap method to run.  That said, if you want to set up running as service, then this is an exercise for you, and if you can contribute your steps for the FAQ, then that would be greatly appreciated.

**Comment by JackDandy** [comment]
The `service` is not required when running with snap, all of the hard work of getting snap working is complete and tested, it was also tested and verified by a Snapcraft member. So I have no idea what is going on with your particular environment as to why it says, **command not found**.  

That said, if you want to set up running as service, then this is an exercise for you, the foundation is there, and if you can contribute to the FAQ, then that would be greatly appreciated.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
