### ISSUE TITLE
Deleting shows doesn't work.

### ISSUE THREAD

**Issue by ryanneufeld** [SickGear/SickGear#1153]
#### Branch version commit hash: (See the About page)

Expectation | Result
That deleting a show would delete the show | it does not.

**Steps to reproduce:**
*1)* Try deleting a show.
*2)* Notice that the show seems to re-appear and continue downloading.
...

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
Sounds very much like you need to read [Files not deleted as expected OR [Errno 13] Permission denied](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#deletechecks)

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
