### ISSUE TITLE
(Minor priority) Feature request: pyOpenSSL to generate certificate

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#1156]
Minor feature request

Certs have been an option for years but I hear a lot of people ask how to generate them, it takes a while to let someone generate a CA while it's pretty easy to do. It could easily be coded in using libraries from pyOpenSSL (or just git the real OpenSSL) and generate them from a drop down menu with the preferred RSA level even for multi-level CA's and they don't even have to be self-signed (which is more then good enough) anymore, it can all be done for free with a few quick commands.
People often want to visit SG remotely or they want to be sure their LAN isn't compromised and use a cert to be sure about that. 
This is a question, because it's a basic option without any explanation, I get from a lot of people setting it up.

My idea to actually add it as a user friendly interface option is to run the basic commands with pyOpenSSL (or OpenSSL, they're both a git away), add a scheduled "git update" to the basic routine to make sure nobody complains about using 1.1.1h instead of 1.1.1j (example) and add 3 simple drop down options to "git" the initial packages required then a "please wait" and spinning circle (which already exists in the distribution) followed by a drop menu with Basic, Very Strong, Extremely strong (RSA1024, RSA2048, RSA4096 you could add the algorithm next to it but "strong" is usually what people look for) then require the activation of username and password so the build=in AES (which could be bumped up to 256) can take care of the rest doing a 1 sec delay query to the CPU for "user friendly"  experience. Request the browser to not store it in cache but in memory and done, the query will determine the required SHA and AES best suited for the NAS/Computer/SoC used.

This is, of course, a feature request and it can go right to the bottom of the to-do list.

Reference for convenience http://pages.cs.wisc.edu/~zmiller/ca-howto/

**Comment by JackDandy** [comment]
I'm no SSL expert, but we do have new code for making _self-certificates_ easier to create.

However, Python does not ship with the latest OpenSSL so 1.1.1 is not even on the radar for many.

External SSL certs can be created with relative ease and added into the settings provided by SG, documentation for doing so is woefully lacking. I can always make documentation more readable, and I enjoy improving on a technical document that is factual, therefore, if you could contribute a step-by-step guide for setting up SSL for the Wiki that answers the questions asked, across the main platforms listed in the wiki install pages, then that is something we can work with, but I'm reluctant to add such a document for only one platform because issues would arise due to incompleteness across all platforms. Either all or none for this subject matter.

**Comment by Th3MadHatter** [comment]
I wouldn't mind at all, I lack time that's why I'm just on every now and then but I'll try and pull out a step-by-step guide and see what can be done by it afterwards, I need to create new certs anyway (about to expire).

What I meant with OpenSSL vs pyOpenSSL is that it's something you just "git", there is no real install process either so just as easy as you make a directory for pyOpenSSL (which is actually used to verify the connections) you can "git" the normal OpenSSL as well, all you need is a directory.
So depending on what is easier to create the files is up to the user of course unless you actually want to implement it as a setting (which you can always do after a guide is written, or leave people to learn something by just using the wiki :) )

Either way I'm going to have a look at it and i'll get back to you about it when I can, it's a no rush thing anyway.
