### ISSUE TITLE
Kodi v18 needs TVDB API v2.0

### ISSUE THREAD

**Issue by Xairoo** [SickGear/SickGear#1162]
Hi,

for Kodi v18 the TVDB API should be updated to v2.0. Also v1.0 is EOL. Looks like SickGear has already v2.0 build in, but it doesn't use it for Kodi or I don't know how to activate it.

More on this thread: https://forum.kodi.tv/showthread.php?tid=323588

Specially the `episodeguide` tags inside the NFO's should be updated.

For example the old one:
`<episodeguide><url cache="((ID)).xml">http://www.thetvdb.com/api/((API-KEY))/series/((ID))/all/en.zip</url></episodeguide>`

New one:
`<episodeguide><url post="yes" cache="auth.json">https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;((API-KEY))&quot;,&quot;id&quot;:((ID))}|Content-Type=application/json</url></episodeguide>`

**Comment by JackDandy** [comment]
Thanks for the report, this will be done ;)

**Comment by JackDandy** [comment]
The info in that link says nfo files will be fine, have you seen a case where the existing data is NOT being used so that i can test a before and after fix ?

**Comment by JackDandy** [comment]
The info in that link says nfo files will be fine, just the url, therefore, can you give a case and the effect where it can be seen that the existing url data is **not** being used so that we can prove a before and after fix is actually working as expected ?

**Comment by Xairoo** [comment]
https://forum.kodi.tv/showthread.php?tid=340712&pid=2821270#pid2821270

**Comment by JackDandy** [comment]
SG has used v2 Api for a long time and the v1 link still works and contains the correct data.

It seems to make a change is not backwards compatible with Isengard, Jarvis, and Krypton, and I do not know how the steps to actually test if any change is making a real difference in Leiea -- we need to be able to see an effect of change, we cant just change the URL and hope for the best.

**Comment by JackDandy** [comment]
SG has used v2 Api for a long time and the v1 link still works and contains the correct data.

It seems to make a change is not backwards compatible with any installations using the older scraper script. I don't know steps to actually test a change is working - yet.

If only the scraper script writer(s) made an XML entity explicitly for v2 Api so that their new scraper could use that link if found -- that would have been a far "nicer" migration approach - as it stands, there is only destructive methods documented.

Reading...

> If you need to keep the NFO file because you've manually edited it, you can convert it to a mixed NFO file by simply adding the TVDB website URL for that show to it somewhere outside the xml (e.g. below everything), and then also removing the incorrect episodeguide URL (including the <episodeguide> tags).
When you refresh, the scraper will use the URL to fetch all the information from the TVDB as normal, but will then overwrite that with the information from xml portion of the nfo file (but not the episodeguide URL, because you removed that, see?).
You should then have the new episodeguide URL and still have all of your edited data. 

So the options are either...
1) replace v1 URL with v2 URL (that you first posted).
2) remove v1 URL and add v2 URL to end of file.

... clearly not a migration path because both methods do not allow earlier scraper script versions to continue using v1 Api even though TVDB have not deprecated v1 since the  2017 EOL date, both options will break older scripts.
 
Conclusion, your method (1) is the best sub-optimal change of the two :(

**Comment by JackDandy** [comment]
This feature will be looked at again when it becomes clear how to determine how Kodi is using tvdb. 

The `ADDON: metadata.tvdb.com v3.0.14` does not contain a Python script, and the `ADDON: script.module.thetvdb v1.0.12` is an Api helper module. 

Adding a video source, pointing directly to one single show and setting it to use TVDb does not produce anything in temp/kodi.log that I can use to prove something is or not happening.  Even with debug log enabled, I cannot determine what is using the .nfo files, I can only see a message that the `full nfo` file is loaded.

Therefore, until this feature actually visibly breaks due to that URL, there's nothing I can sensibly action. If you can find anything more, then that would be useful.

**Comment by JackDandy** [comment]
I tried to recreate the bug you reported [here](https://forum.kodi.tv/showthread.php?tid=340712&pid=2821227#pid2821227) on the Kodi forums and where failure to set the Watched flag was [attributed](https://forum.kodi.tv/showthread.php?tid=340712&pid=2821270#pid2821270) to the nfo file `episodeguide` URL being Api v1. However, my tests failed to prove anything useful because I couldn't get that bug to occur with v1 Api links, I can press 'w' just fine. 

Maybe my error, but I wonder if the blame was a guess, perhaps @KarellenX could suggest something.

**Comment by JackDandy** [comment]
I tried to recreate the symptom you reported [here](https://forum.kodi.tv/showthread.php?tid=340712&pid=2821227#pid2821227) on the Kodi forums and where failure to set the Watched flag was [attributed](https://forum.kodi.tv/showthread.php?tid=340712&pid=2821270#pid2821270) to the nfo file `episodeguide` URL being Api v1. However, my tests failed to prove anything useful because I couldn't get that bug to occur with v1 Api links, I can press 'w' just fine. 

Maybe my error, but I wonder if the blame was a guess, perhaps @KarellenX could suggest something.

**Comment by KarellenX** [comment]
Hello @JackDandy 

I did not investigate the Watched status issue. My responses dealt with the following comment...
> An other show doesn't show up as a show, it just shows a folder icon in the folder list?! Name of show is "The Handmaid's Tale"
> 
> Tried different names too, nothing helped. Cleaned and updated the library all the time.

The reason it did not show in the library is due to v1.0 API episode URL's being used. The Kodi scrapers use v2.0.

Two simple fixes in this situation...
1. delete the tvshow.nfo and let kodi scrape
2. delete the <episodeguide> tag from the tvshow.nfo. This has the drawback of not allowing you to add additional episodes to the show in future.

If members don't have a specific requirement to keep the existing data, then I normally advise that members delete all their nfo files and let Kodi scrape the show.

**Comment by JackDandy** [comment]
Hiya @Xairoo 

Now is time to make this change, are you available ?

**Comment by JackDandy** [comment]
@KarellenX 

Hi,

So the nfo processing is changing here, where we are outputting a new nfo file with latest changes.

in this we see your tvdb show scraper thread for ... https://forum.kodi.tv/showthread.php?tid=349385 

In Python, the xml lib will output XML legal which means a conversion of `&` to `&amp` given that `&` is not valid xml.

however, documented here `https://forum.kodi.tv/showthread.php?tid=323588`
is to output to the nfo, template...
The v2.0 guide looks like this... `<url post="yes" cache="auth.json">https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;439DFEBA9D3059C6&quot;,&quot;id&quot;:80379}|Content-Type=application/json</url>`

the concern is the all those non valid uses of `&`. Those are converted by Python etree/lxml to the proper values which appears like so...
```
  <episodeguide>
    <url cache="auth.json" post="yes">https://api.thetvdb.com/login?{&amp;quot;apikey&amp;quot;:&amp;quot;((API_KEY))&amp;quot;,&amp;quot;id&amp;quot;:80379}|Content-Type=application/json</url>
  </episodeguide>
```
My question is, if you are aware of this, does you plugin convert `&amp;quot;` back to `"` ?

It could be that it doesn't, and therefore, things just won't work. 

I hope this makes sense.

**Comment by JackDandy** [comment]
@KarellenX 

Hi,

So the nfo processing is changing here, where we are outputting a new nfo file with latest changes.

In Python, the lxml/xml lib will output XML legal which means a conversion of `&` to `&amp` given that `&` is not valid xml. It will do this correction when an attribute it used when creating a node. For example, Kodi docs request attributes `cache` and `post` be used in the `url` node.

However, documented [here](https://forum.kodi.tv/showthread.php?tid=323588) is the nfo, template...
> The v2.0 guide looks like this... `<url post="yes" cache="auth.json">https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;439DFEBA9D3059C6&quot;,&quot;id&quot;:80379}|Content-Type=application/json</url>`

the concern is the all those non valid uses of `&`. Those are converted by Python etree/lxml to the proper values which appears like so...
```
  <episodeguide>
    <url cache="auth.json" post="yes">https://api.thetvdb.com/login?{&amp;quot;apikey&amp;quot;:&amp;quot;((API_KEY))&amp;quot;,&amp;quot;id&amp;quot;:80379}|Content-Type=application/json</url>
  </episodeguide>
```
My question is, if you are aware of this, does you plugin convert `&amp;quot;` back to `"` ?

It could be that it doesn't, and therefore, things just won't work with your tvdb show scraper thread ... https://forum.kodi.tv/showthread.php?tid=349385 

I hope this makes sense.

**Comment by JackDandy** [comment]
Hi @KarellenX 

So the .nfo file processing is being updated here. We are aiming to output new nfo file(s) to follow latest Kodi requirements.

In Python, the lxml/xml lib will output XML legal - this means a native conversion of `&` to `&amp` given that `&` is not valid xml. 

However, documented [here](https://forum.kodi.tv/showthread.php?tid=323588) is the Kodi nfo template, quote...
> The v2.0 guide looks like this... `<url post="yes" cache="auth.json">https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;439DFEBA9D3059C6&quot;,&quot;id&quot;:80379}|Content-Type=application/json</url>`  

the concern is all those non valid uses of `&` because Python etree and lxml converts those to xml values when an attribute is used during xml node creation.  The above Kodi template shows attributes `cache` and `post` being used in the `url` node, and so the nfo file output result appears like so...
```
  <episodeguide>
    <url cache="auth.json" post="yes">https://api.thetvdb.com/login?{&amp;quot;apikey&amp;quot;:&amp;quot;((API_KEY))&amp;quot;,&amp;quot;id&amp;quot;:80379}|Content-Type=application/json</url>
  </episodeguide>
```
My question, are you aware of this, does the TVDB scraper plugin convert `&amp;quot;` back to `"` ?

It could be that it doesn't, and therefore, nfo files output by Python and other langs may not work with your tvdb show scraper, this one [here](https://forum.kodi.tv/showthread.php?tid=349385) 

I hope this makes sense.

**Comment by JackDandy** [comment]
Hi @KarellenX 

So the .nfo file processing is being updated here. We are aiming to output new nfo file(s) to follow latest Kodi requirements.

In Python, the lxml/xml lib will output XML legal - this means a native conversion of `&` to `&amp` given that `&` is not valid xml. 

Standard Python code...
```
tv_node = etree.Element('tvshow')

episodeguide = etree.SubElement(tv_node, 'episodeguide')
episodeguideurl = etree.SubElement(episodeguide, 'url', post='yes', cache='auth.json')
episodeguideurl.text = 'https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;((APIKEY))&quot;,&quot;id&quot;:((SHOWID))}|Content-Type=application/json'
```
where;  
`((APIKEY))` and `((SHOWID))` are the replacement variable placeholders
and...  
etree is either one of ... `import xml.etree.cElementTree as etree` (native lib) or `from lxml import etree`

However, documented [here](https://forum.kodi.tv/showthread.php?tid=323588) is the Kodi nfo template, quote...
> The v2.0 guide looks like this... `<url post="yes" cache="auth.json">https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;439DFEBA9D3059C6&quot;,&quot;id&quot;:80379}|Content-Type=application/json</url>`  

the concern is all those non valid uses of `&` because Python etree and lxml converts those to xml values when an attribute is used during xml node creation.  The above Kodi template shows attributes `cache` and `post` being used in the `url` node, and so the nfo file output result appears like so...
```
  <episodeguide>
    <url cache="auth.json" post="yes">https://api.thetvdb.com/login?{&amp;quot;apikey&amp;quot;:&amp;quot;((API_KEY))&amp;quot;,&amp;quot;id&amp;quot;:80379}|Content-Type=application/json</url>
  </episodeguide>
```
My question, are you aware of this, does the TVDB scraper plugin convert `&amp;quot;` back to `"` ?

It could be that it doesn't, and therefore, nfo files output by Python and other langs may not work with your [tvdb show scraper](https://forum.kodi.tv/showthread.php?tid=349385)

I hope this makes sense.

**Comment by KarellenX** [comment]
Hello @JackDandy 

As much as I would like to answer your technical questions, I am not a developer so I don't have the technical understanding to help out.

The scraper in current general use for v18 is XML based. @olympia might be able to answer your questions here.

Both @Razzeee or @romanvm are developing Python based scrapers which will be used for v19 and later and they might be able to provide advice also.

**Comment by JackDandy** [comment]
Hi @KarellenX

You can help greatly if you can find out whether the `episodeguide` output works or not. Copying/pasting with your API key and a show_id the converted valid xml to see if the tvdb scrapers perform as you _know_ them to - I am not familiar with these things and would appreciate existing knowledge of those tools so I can continue without worry.

**Comment by JackDandy** [comment]
Hi @KarellenX 

Here is an issue myself and a user have independantly found, I  found it before xmas but ignored it as a user error until another reported it to me.
  
* One system is pure Kodi on Ubuntu
* Another is Kodi on LibreElec
* No issue on Kodi Windows
  
Navigate to Video/files in the context menu of a folder, "Change content" type to "TV Shows". 
In the same "Change content" menu -> switch "information provider" between "local" and "tvdb" click "OK" then "Yes" when asked to scan folders .. **will yield a complete system crash**. 

Crash log final lines...
```
2020-01-11 09:50:09.181 T:1937595936   DEBUG: ------ Window Init (DialogExtendedProgressBar.xml) ------
2020-01-11 09:50:09.204 T:1799328624  NOTICE: VideoInfoScanner: Starting scan ..
2020-01-11 09:50:09.204 T:1937580912   DEBUG: CAnnouncementManager - Announcement: OnScanStarted from xbmc
2020-01-11 09:50:09.205 T:1937580912   DEBUG: GOT ANNOUNCEMENT, type: 16, from xbmc, message OnScanStarted
2020-01-11 09:50:09.256 T:1608250224  NOTICE: EMBY.hooks.monitor -> -->[ kodi scan/video ]
2020-01-11 09:50:09.258 T:1608250224  NOTICE: EMBY.objects.monitor -> [ xbmc/VideoLibrary.OnScanStarted ]
2020-01-11 09:50:09.371 T:1799328624   DEBUG: CSMBFile::Open - opened smb://USERNAME:PASSWORD@<ip_redacted>/Video/tv/Burden of Truth/tvshow.nfo, fd=10000
2020-01-11 09:50:09.381 T:1799328624   DEBUG: CSMBFile::Close closing fd 10000

############### END LOG FILE ################

############ END kodi CRASH LOG #############
```
After research, I updated Kodi to latest 18.5, and also TVDB addon to 3.2.3 - still crashed.  
I then started dismantling `tvshow.nfo` and `media_file_name.nfo` and found that...  
if the attribute `default=""` is removed from a tag, then the crash does **not** occur.

See...
https://i.vgy.me/ZkP1Xe.png

`default=""` can also be found in xml tag `uniqueid` in file tvshow.nfo, as well as xml tag `ratings` - both occurrences cause a black screen crash and system reboot.

I place this note here so at least _you_ have a record.  SG will remove those attributes and advise users not to use any .nfo creation addon if they also experience system crashes with Kodi. That's about as much as I can do given only you gave a comment last time.

**Comment by KarellenX** [comment]
I am using a Windows system, so I am not able to replicate the issue.

Looking at your nfo file extract, I have to state that is not a Kodi scrape. In fact I am hard pressed to believe that nfo file came from Kodi at all. 

This is a Kodi nfo file... https://paste.kodi.tv/neqawevalu 

Can you see the differences? In fact what you state in your image as proving that the nfo file was created by Team Kodi, actually proves the opposite. But I also notice a mention of Emby in the partial debuglog. Emby does something different, and I cannot debug Emby issues.

Please, if you want to debug Kodi, it has to be standalone Kodi, not a Kodi being used as a front end for another media centre.

The **default** item is required for both UniqueID and ratings. It is a simple "yes" or "no".  Kodi is actively looking for the default item which, in your example, there is none. If you have multiple Ratings and UniqueID entries one, and only one, of each **must** be marked as default

**Comment by JackDandy** [comment]
Thanks for the feedback.

Like i said, the other user has a pure Kodi (never used Emby) with the same symptom. 
Also, as reported, we tested and proved the issue does not happen on Windows.
I also did tests with Emby removed, same symptom. 

However, when I used **your** nfo, and changed the `default="true"` (not "yes") to `default=""` in the rating tag, switched provider to `tvdb`, and clicked "Yes" to a content scan, I replicated the same crash. Changing your nfo back to `default="true"`, then switching back to `local` produced no crash. Therefore, there is something in there that when a default tag does not confirm to what Kodi expects, it will system crash.

Again, do not read anything about Emby being in there, like i said, the crash was proven without it.  

I think we agree when you say that there MUST be `default="true"` - but I am making you aware that on some systems, if there isn't,  Kodi will system crash - and that is probably not desired.

**Comment by KarellenX** [comment]
oops, what was I thinking!! You are correct it should have been "true" "false" not yes/no as I stated.

Let me follow your steps again and see if I can confirm the crash

**Comment by KarellenX** [comment]
Sorry, but I just cannot replicate the crashing issue. In fact Kodi is allocating the first rating in the list as default=true even when it is missing the default attribute.

Can you provide me a debug log which captures the crashing, and it might show the cause.

**Comment by JackDandy** [comment]
Bah! I didn't expect you would. Yeah, there is nothing in the log to indicate error, simply what I posted - this is why i was reluctant to even post it, even blamed myself and Emby, but because another individual also replicated it *plus* I can control it from not happening, then I thought I would mention it.

Unfortunately, there's nothing to show causality in the crash logs - it's not like there is an exception being thrown or something useful like that - can see the `.nfo` file being read, then the log simply ends.

Well, bear this in mind and if someone else mentions it, check their `default` attributes :)

I must now write some lines to parse and remove the attributes from systems using SG - fun!

**Comment by JackDandy** [comment]
@KarellenX 

Additionally, someone has just brought to my attention the same findings posted [here](https://discourse.osmc.tv/t/crash-when-updating-library/83764) take note of **comment #8** and another user [here
](https://discourse.osmc.tv/t/vero-4k-and-pi3-rebooting-after-scan-to-library/83879/12) **comment #12**

Looks like there is defo something up.

**Comment by JackDandy** [comment]
@KarellenX 

Additionally, someone has just brought to my attention the same findings posted [here](https://discourse.osmc.tv/t/crash-when-updating-library/83764) take note of **comment 8** and another user [here](https://discourse.osmc.tv/t/vero-4k-and-pi3-rebooting-after-scan-to-library/83879/12) **comment 12**

Looks like there is defo something up.

**Comment by KarellenX** [comment]
Interesting. Thanks for the links. I will contact Sam and see if he has diagnosed the problem in OSMC

We are a bit shy on active developers at the moment so I know nobody is going to jump up and volunteer for this issue which has a workaround - ie correct nfo files. I know, not ideal.
