### ISSUE TITLE
Unable to login to TheTVDB API

### ISSUE THREAD

**Issue by laurentgrangeau** [SickGear/SickGear#1163]
#### Branch: The name of the branch (e.g. master or develop)
master
#### Branch version commit hash: (See the About page)
f70063e31712d5e9f9bef2e9e1e1934935d7331e

Expectation | Result
------------ | -------------
Search for a show, the show is being fetch from TheTVDB API. | 2019-02-21 18:41:28 DEBUG    SHOWQUEUE-ADD :: Response not ok. 403: Forbidden from requested url https://api.thetvdb.com/login (...2 repeat lines) <br /> 2019-02-21 18:41:28 INFO     SHOWQUEUE-ADD :: TheTVDB: {'apikey': 'F9C450E78D99172E', 'cache': '/opt/sickgear/data/cache/indexers/TheTVDB', 'language': 'en'} <br />2019-02-21 18:41:28 INFO     SHOWQUEUE-ADD :: Starting to add show /tmp/The Simpsons

**Steps to reproduce:**
*1)* Search for a show
*2)* Don't see the result

This seems to appear because of the simple quote sent to the API. I'm able to reproduce it with the Swagger API --> https://api.thetvdb.com/swagger#!/Authentication/post_login

**Comment by JackDandy** [comment]
Looking at your steps is way too basic a step to not work, in fact search for show "the simpsons" produces results fine.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by laurentgrangeau** [comment]
Hi @JackDandy, how can I transform this simple in double quote ? I try modifying indexes_api.py without success...
I guarantee you that I can't add a show. I know this is basic steps, but it definitively won't work.
I also try to put single quote to the Swagger API, and I can reproduce the error. With double quotes, it works...

**Comment by laurentgrangeau** [comment]
As per you screenshot, this is after the "finally" step, when the show is being processed. It can't scape the show, nor the image, and after that, the show disappear from the list.

**Comment by JackDandy** [comment]
Look, can you clearly send all the steps to replicate an issue, we have used 40 minutes already.

**Comment by JackDandy** [comment]
@laurentgrangeau The log line that you sent, and talking of the single quote, has nothing to do with your issue, you are mistaken.

The actual 403 error is a genuine **access forbidden** code from the tvdb server.

Most likely that tvdb has blocked your ip ... perhaps, due to too many hits to the server or abuse (can be a different app that curses that IP block or even someone that shares the ip) or maybe you are using proxy or VPN.

These are educated guesses, but still, your issue is *not* one that is caused by SickGear.

Good luck.

**Comment by laurentgrangeau** [comment]
Actually, you're right. I trigger the CloudFlare DDOS response and I can't respond to the captcha.
I think this IP is blacklisted from CloudFlare.
