### ISSUE TITLE
SG does not understand that there are new TV Show episode release

### ISSUE THREAD

**Issue by benzoto** [SickGear/SickGear#1164]
Version: | BRANCH: master / COMMIT: 9238db3 @ 0.18.16 		
		This is BETA software
-- | --
Config file: | /opt/sickgear/data/config.ini
Database file: | /opt/sickgear/data/sickbeard.db

No new TV-Show releases for certain TV Shows. There are shows which are working OK but for some no updates are happening. Full Update does not do anything as well

**Comment by JackDandy** [comment]
The steps section requested when this issue was created, enables your reported issue to be replicated and investigated, however, you removed it so there is no idea how to trigger your reported event in order to fix it for you. Until you can supply this information, then there is no choice but to mark this issue "invalid" as what you are reporting cannot be verified. Sorry.

Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

There's no need to open a new issue, additions to the end of this thread are just fine.

Thanks.
