### ISSUE TITLE
Feature Request: Update show location via API

### ISSUE THREAD

**Issue by Scapponian** [SickGear/SickGear#1180]
#### Branch version commit hash: latest

Expectation | Result
------------ | -------------
Option via API to change file system location of the show.

When changing storage devices for a large library, it is very tedious to have to do this manually via the interface.

Thank you # #

**Comment by JackDandy** [comment]
FR is added to the list.

Thanks.

**Comment by JackDandy** [comment]
> it is very tedious to have to do this manually via the interface.

How is it tedious, it is not as though this is an often done operation, and Manage/Mass Edit will do many shows in the one hit, therefore, tedium is a far stretch.

**Comment by JackDandy** [comment]
In light of no response, here's my thought about this request ... theoretically, an attacker could change a location to a `/vulnerable/auto_run/location/` and then post processed a file into that place in order to successfully execute an attack or whatever with this feature.

For this reason, this issue will be closed as a 'wont fix'.
