### ISSUE TITLE
Post-Processing Error - "Cannot find attribute 'contentrating'"

### ISSUE THREAD

**Issue by BradMN** [SickGear/SickGear#1182]
#### Branch version commit hash: d1166f9 @ 0.19.0

Expectation | Result
------------ | -------------
Clean post process of known good media files | Consistently get the contentrating error during the processing phase

**Steps to reproduce:**
*1)* Import a known good media file
*2)* Upon completion, get error screen in the attached file

[File removed: PDF is not allowed, see below)

**Comment by JackDandy** [comment]
I cannot look at the PDF. Please look at the followign link for how to post logs so that you can be helped.

Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

There's no need to open a new issue, additions to the end of this thread are just fine.

Thanks.

**Comment by BradMN** [comment]
Here is the HTML output:
https://gist.github.com/BradMN/0cc8694f06021eae160417e2a5d17ee9

Here is the LOG file output:
https://gist.github.com/BradMN/34753590b8b40082c2f17f526cd71b1b

I should also note that when attempting to process a folder with several episodes, this error causes the post-process to stop after each episode is moved to the destination directory.

**Comment by JackDandy** [comment]
Fixed [0.19.1](https://github.com/SickGear/SickGear/releases/tag/release_0.19.1)
