### ISSUE TITLE
Post Processing Issue

### ISSUE THREAD

**Issue by ilangers** [SickGear/SickGear#1185]
#### Branch version commit hash: 1180c23 @ 0.19.5

Expectation | Result
-------- |  ---------
I am running SickGear on Synology. After a TV show downloads, the sabToSickBeard script runs and sorts files appropriately. | The script has the following error. This only started happening after updating SABnzbd.

**Steps to reproduce:**
*1)* After checking the History in SABnzbd I see that the post-processing has failed with error "Exit(1) AttributeError: ’module’ object has no attribute ’Session’ (More)" 
*2)* Clicking 'more' gives the full error:
Loading config from /usr/local/sickbeard-custom/var/SickBeard/autoProcessTV/autoProcessTV.cfg

Opening URL: http://localhost:8081/home/postprocess/processEpisode
Traceback (most recent call last):
File "/usr/local/sickbeard-custom/var/SickBeard/autoProcessTV/sabToSickBeard.py", line 30, in <module>
autoProcessTV.processEpisode(sys.argv[1], sys.argv[2], sys.argv[7])
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/autoProcessTV/autoProcessTV.py", line 138, in processEpisode
sess = requests.Session()
AttributeError: 'module' object has no attribute 'Session'

*3)* I have followed this - https://github.com/SickGear/SickGear/issues/1029 - already without success.
*4)* This only appears to have happened since updating to SABnzbd 2.3.8 on my Synology NAS.
*5)* Possible pertinent information - Python Version: | 2.7.14 (default, May 28 2018, 15:26:34) [GCC 4.3.2]
*6)* Also, if I go to http://localhost:8081/home/postprocess/processEpisode and manually run the 'process' it all works successfully.

Thanks in advance.

Langers

**Comment by JackDandy** [comment]
So, on reading...

Your point 6) Everything from the runtime perspective of SG is working fine

Your point 3) The script running from SAB perspective is now failing. The failure seems to be missing modules, and by the looks of it probably `Requests`. You need to handle that.
Alternatively, stop using the `sabToSickBeard.py` and set up SG post processing settings to check the SAB completed folder instead.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
