### ISSUE TITLE
Processing issues since 6/7 update 0.19.2 - "prevent post processing under a parent (or show root) folder"

### ISSUE THREAD

**Issue by dabug911** [SickGear/SickGear#1194]
#### Branch version commit hash: BRANCH: master / COMMIT: 5162633 @ 0.19.6

Expectation | Result
------------ | -------------
Prior to the update of 0.19.2 all of my post processing worked fine. Sabnzbd posts the files into my /tv/ root folder, then the post processing scripts would process the media and update plex accordingly. Since this update it appears this option has been disabled, can this be changed? | Since update to 0.19.2 all of my post processing fails.

Prior to the update this is the output I was seeing (truncated)
<pre>Loading config from /opt/sickgear/autoProcessTV/autoProcessTV.cfg

Opening URL: http://localhost:10001/home/postprocess/processEpisode
Checking folder... /home/eraver/Media_Volume/SB/TV/In.the.Dark.2019.S01E10.HDTV.x264-SVA
Processing folder... /home/eraver/Media_Volume/SB/TV
Processing sub dir: In.the.Dark.2019.S01E10.HDTV.x264-SVA
Processing... 9fk4BUtjHq.mkv
.. from nzb In.the.Dark.2019.S01E10.HDTV.x264-SVA.nzb
Found a match in history for In the Dark (2019)
Parsed In the Dark 2019 - S1E10 [GROUP: SVA] [ABD: False] [ANIME: False] [whichReg: ['standard']]
.. from In.the.Dark.2019.S01E10.HDTV.x264-SVA.nzb
</pre>
Post the update to 0.19.2 and above it now checks out...
<pre>
Loading config from /opt/sickgear/autoProcessTV/autoProcessTV.cfg

Opening URL: http://localhost:10001/home/postprocess/processEpisode
Checking folder... /home/eraver/Media_Volume/SB/TV/Animal.Kingdom.US.S04E05.WEBRip.x264-TBS
Dir /home/eraver/Media_Volume/SB/TV/Animal.Kingdom.US.S04E05.WEBRip.x264-TBS is subdir of show root dir: /home/eraver/Media_Volume/SB/TV, not processing.
</pre>

Additional notes:
I've been able to redirect my downloads to a temp folder then have post processing applied, however this only works if the show is in my sickgear already and even then i am noticing a hire failure rate. Since this change was introduced recently i'm curious if there is a way to disable it or to get the version prior to this and step sickgear back and turn off autoupdate.

**Comment by dabug911** [comment]
If it helps, it appears the changes were made to processTV.py/pyc, if there is a way to get this file prior to those changes and there are no other files required I can just revert that file.

**Comment by JackDandy** [comment]
Hello,
  
You have a parent folder that contains processed items...
`/home/eraver/Media_Volume/SB/TV/`
  
and you are downloading directly to...
`/home/eraver/Media_Volume/SB/TV/`
  
You have managed to get away with this when what you are downloading is a dir like...
`/home/eraver/Media_Volume/SB/TV/Animal.Kingdom.US.S04E05.WEBRip.x264-TBS`
  
However, it has been found that this is a dangerous situation under some configurations because it can lead to the undesired outcome where all files under /TV/ can be "cleaned up", that is deleted. This is why that defensive code was added. Now, you are sailing dangerously close to this cliff edge, and this is the cliff that 19.2 is there to guide you back from.

The correct course of action is not to remove the protection, but instead, for you is to change your client downloader path from...  
`/home/eraver/Media_Volume/SB/TV/`

to something like...
`/home/eraver/Media_Volume/Incoming/`
 
and then you will be fine. Now you said you tried to change the path and you seem to be getting more failures, that seems strange, perhaps you didn't fully reconfigure your setup for the new download location.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
