### ISSUE TITLE
"Upgrade qualities" should automatically reset to null when user changes quality from custom to anything else

### ISSUE THREAD

**Issue by tomwitt2** [SickGear/SickGear#1196]
#### Branch: The name of the branch (e.g. master or develop)
BRANCH: develop
#### Branch version commit hash: (See the About page)
COMMIT: c0e29a2 @ 0.20.0

Expectation | Result
------------ | -------------
Your expectation paragraph(s) text here. Before the bar >> | then, your result paragraph(s) text here.
If I've saved a custom quality profile, and I've included any upgrade qualities, then I come back and I choose to switch from custom to one of the default quality profiles, I'm clearly indicating that I don't want a custom profile anymore.  My upgrade quality preferences should be cleared if they are going to impact my ability to set (and retain) my newly preferred default quality | Repeatedly, I've tried to change to a default quality setting profile (Hd720) and, inexplicably, the custom profile would remain selected.  It wasn't until I read the closed bugs (which referred me to the FAQ), that you can't choose a default profile (like Hd720, and have it stick UNLESS you first clear all the upgrade qualities.  This is not intuitive and frustration inducing.  Pehaps even having a "clear upgrade qualities" checkbox or prompt would help

**Steps to reproduce:**
*1) Set a custom quality profile, set upgrade qualities, save as default

*2) Set a quality using one of the presets (HD720), save as default (without clearing custom upgrade qualities)  Custom profile is retained.

**Comment by JackDandy** [comment]
>  that you can't choose a default profile (like Hd720, and have it stick UNLESS you first clear all the upgrade qualities. 

Yes, this is correct logical behavior, if a custom setting is not the same as a default, for example, hd720 with an upgrade quality set, then changing the UI to 720 will not render the 720 default option, because, well, it is _not_ the 720 default, it is a custom (because you have, in this example, an upgrade quality set).

However, this is labelled "Enhanced" as a feature request as this is not a bug, but perhaps something could be added to override a default. Perhaps on clicking "Save default" something like a confirm dialog with two button options, [Abandon custom for default] or [Update custom setting] .. this needs to be considered more.
