### ISSUE TITLE
Unable to choose folder in 'show root directories'.

### ISSUE THREAD

**Issue by NewAgeRetroHippi** [SickGear/SickGear#1198]
#### Branch version commit hash: snap @ 0.20.1

Expectation | Result
------------ | -------------
Using a fresh install of Ubuntu 18.04, I expected to be able to choose a folder in the "show root directories" section.  I made sure to chmod -R 777 /mnt to allow all users access to the folder... | When clicking on /mnt it does not show any folders inside.  There are only particular folders that it is able to open.  It can open: /proc, /lib, /etc.  It cannot open: /lib64, /mnt, /opt.

**Steps to reproduce:**
*1)* Install.
*2)* chmod to give access to a folder to all users.
*3)* Try to open folders in "show root directories".

**Comment by JackDandy** [comment]
Owenership/ Umod ? This is likely an OS issue, there is nothing in SG that targets folders to not list them, therefore, i can only think this is an OS issue.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
