### ISSUE TITLE
Misidentification

### ISSUE THREAD

**Issue by shortbus** [SickGear/SickGear#1199]
#### Branch version commit hash: 48c312b @ 0.20.2

Expectation | Result
------------ | -------------
Saw that season 02 was not injested. Ran force process with replace on only the Season 2 directory.
|

In the log I saw it misidentified

Found release name Misfit.Garage.**S02E05**.A.31.Ford.Hot.Rod.And.71.Holy.Grail.Cuda.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb
Destination folder for this episode is /mnt/fileshare/plex/TV_Shows/Misfit Garage/Misfit.Garage.Season.**03**
Copied file from /mnt/fileshare/Torrents/deluge_tvshows_dupe_import/post_ingest_double_check/Misfit.Garage.S01-S05.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb/Misfit.Garage.**S02**.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb/Misfit.Garage.**S02E05**.A.31.Ford.Hot.Rod.And.71.Holy.Grail.Cuda.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv
.. to /mnt/fileshare/plex/TV_Shows/Misfit Garage/Misfit.Garage.Season.03/Misfit.Garage.**S03E05**.57.Corvette.Part.1.1080p.WEB-DL-NTb.mkv
Successfully processed Misfit.Garage.**S02E05**.A.31.Ford.Hot.Rod.And.71.Holy.Grail.Cuda.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv
Processing... Misfit.Garage.S02E07.The.Race.To.Finish.The.71.Holy.Grail.Cuda.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv
Parsed Misfit Garage - **S3E7** [GROUP: NTb] [ABD: False] [ANIME: False] [whichReg: ['standard']]
.. from Misfit.Garage.**S02E07**.The.Race.To.Finish.The.71.Holy.Grail.Cuda.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv

**Steps to reproduce:**
*1)* process directory

**Comment by JackDandy** [comment]
Instead of processing at the level `/Misfit.Garage.S01-S05.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb` instead try processing `Misfit.Garage.S02.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb`.

**Comment by JackDandy** [comment]
It is not misidentification, seems you neglected to add that you have `Editable episode numbers` enabled for that show ;-) That ep number by scene is **indeed** TVDB Season 2 - on the display show page, click the xem icon top right and you can find the show and see the episode mappings for yourself.   Also, in the show view, the alt number for `s03e07` should be `2x7` to indicate what to expect from processing/search.
  
Sadly, I also hear that the release numbering for this show may be messy, which means that there are releases with correct numbering and others with alternate numbering, you can see which is which on the example eps that you have by matching up the names of the episodes with those sxxexx numbers with whatever is set in SG. Then find the release group that matches whichever numbering you use (editable - using thexem, or not), and allow only that group to snatch using the option `Require at least one word` with the release groups that you find fits the numbering that you are using.   
  
Btw, instead of processing at the level `/Misfit.Garage.S01-S05.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb` instead try processing `Misfit.Garage.S02.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb`, and then `Misfit.Garage.S03.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb`.
This is just a tip.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
