### ISSUE TITLE
Feature request: Add Anime rename button

### ISSUE THREAD

**Issue by JackDandy** [SickGear/SickGear#1206]
This request is a re-post + reply here...

A request from @Merwenus was to add an separate button to rename Anime.

---

@Merwenus The rename function is applied to any known media file that is not named in the current naming pattern that exists in "Episode Naming" settings.

There are separate anime naming pattern preferences that are applied to media of that type.

By design, the rename function is simple with one button, instead of overkill with a separate button for each available media type (episode, air-by-date, sports, anime). 

Simply set up how you want stuff to be named and don't worry about if the show is anime or whatever, just rename and SG takes care of it.

**Comment by Merwenus** [comment]
I think you misunderstood it. 
As a hungarian I use 3 renaming pattern, and can't achieve what you suggest.

1) Hungarian Series are with this pattern (usually Flexget renames them):
%SN - s%0Se%0E - %EN

2) English series are untouched, because Kodi+subtitle addons need the original file name to get the synced subtitle, that means I can't rename it.

3) And there are Animes, where I need them to rename (for Kodi) to understand, because most animes are using XY series **e567**, but on TVDB what Kodi uses it is **s10e46**, and Kodi does not understand the e567 form, it needs s00e00. Flexget does it very well, but there are less and less translator who put it on torrent, and I download them manually to the download folder (where SG post process files), and SG just simply copy the files without touching it and Kodi just ignores these until I rename them to the correct form.

What you suggest, would either:
1) Wreck Kodi downloading subtitles.
2) Wreck Kodi to recognize anime correctly.

There is no between, and that is Why I posted this request to let us IGNORE series but post-process anime with rename. I know it is not a big deal when you are good in english/japan, but as a hungarian I know a little English and zero Japan. :)

**Comment by JackDandy** [comment]
I have not misunderstood, you can achieve all that you want. 

Simply set the **non anime** to rename using  `%RN` so that the original **R**elease **N**ame is used, therefore this will not affect Kodi, and then set Anime however you want as I already said.

**Comment by JackDandy** [comment]
I have not misunderstood, you can achieve all that you want. 

Simply configure **non anime** to custom pattern with `%RN` so that the **_original_** **R**elease **N**ame is used, therefore this will not affect Kodi, and then set Anime however you want. The little help icon to the right of the custom rename input box shows the availability of `%RN` plus others.

For example, `Season %0S\%RN` will place files in tidy season folders under showname with original release names preserved.

Hope this helps.

**Comment by Merwenus** [comment]
Tested what you suggested and it doesnt work well.
It renames normal series using %RN from **Silicon Valley - s06e02 - Blood Money.mkv** to
**Silicon.Valley.S06E02.Blood.Money-SickGear.mkv**

Not to talk about that Since then even the English series stopped auto downloading subtitles in kodi because of this name pattern.

So I still ask for a feature to allow rename ONLY animes and skip normal episodes, or give an option to use original file name instead of %RN for normal episodes. Thank you

**Comment by JackDandy** [comment]
Try to disable rename episodes under file handling in the post processing settings.

How is that for you?

**Comment by Merwenus** [comment]
Won't it disable anime renaming too completely? Because that part is working like a charm, and I need to rename only animes, but keep every other series intact.

**Comment by JackDandy** [comment]
hmm, ok yeah, you're right. So, for normal tv shows, if %rn is not what you want, then surely the existing tokens can be made so that kodi will be fine - i mean i have no issue with kodi parsing filenames.

**Comment by Merwenus** [comment]
Kodi SuperSubtitles (hungarian) addon works well only, if the uploaded subtitle has the same name as the video file and if I rename it in any way it won't download automatically, and they are not always looks the same sadly. There are 3-6 subtitles for the same episode and kodi not always shows the whole subtitle names, that means when I'm unlucky I have to download all 6 subtitles to see which one is synced with the release. When I don't rename, I just press the subtitle button and it downloads automatically. But also Kodi (TVDB) hates animes, and when I put something new in the folder, it just ignores until I rename it to s01e01 format...

And this is why I posted this feature requests, to make it Anime renames automatic but don't screw the kodi subtitle management.
