### ISSUE TITLE
Subliminal problem

### ISSUE THREAD

**Issue by BhaalM** [SickGear/SickGear#1215]
#### Branch version commit hash: c69affb

Expectation | Result
------------ | -------------
Select different subtitle languages to download | Downloads only english subtitles even if the subtitles exist in other languages in opensubtitle.org

**Steps to reproduce:**
*1)* Open subtitle config
*2)* Select more than one language 
*3)* Click to download all subtitles

I've checked the subtitles in that language exists but subliminal only downloads english subtitles. I could try to solve this issue myself but I don't know how to redirect subliminal log message to the sick rage log file. Any help would be appreciated.

Regards

**Comment by JackDandy** [comment]
I'm going to close this because we have made changes to Subliminal in the following [branch](https://github.com/SickGear/SickGear/pull/1200) which will go live before the end of January.  You are welcome to test if your issue exists on this branch and feedback, otherwise you can wait and then report back when that branch is merged (if you need to).

**Comment by BhaalM** [comment]
I'll try the new branch thank you. Ok, I'll try the new branch. Any advice on how to send subliminal debug log messages to the sickgear log file?

**Comment by JackDandy** [comment]
Unfortunately, It's not as trivial as logs. This is exactly why we ask for steps to replicate the issue, because if you communicate those steps clearly, then we are able to load things up in a dev system and freeze/step through the code while replicating your issue in order to pinpoint an exact cause.

**Comment by BhaalM** [comment]
I understand, thank you anyway (for your help and for your work on this project)

**Comment by BhaalM** [comment]
I found the problem, it seems the spanish subtitles of opensubtitles lack a lot of information (no video hashes) so I changed the **list_checked** function:

https://github.com/SickGear/SickGear/blob/8df3c5b9640edbcf4d3098b49ea1e5d445dc9184/lib/subliminal/services/opensubtitles.py#L133-L143 

to:

    def list_checked(self, video, languages):
        results = []
        if video.exists:
            results = self.query(video.path or video.release, languages, moviehash=video.hashes[\'OpenSubtitles\'], size=str(video.size))

        if not results:
            if video.imdbid:
                results = self.query(video.path or video.release, languages, imdbid=video.imdbid)
            elif isinstance(video, Episode):
                results = self.query(video.path or video.release, languages, query=video.series)
            elif isinstance(video, Movie):
                results = self.query(video.path or video.release, languages, query=video.title)
        return results

I know I'll may download out of sync subtitles, but I prefer this.

**Comment by JackDandy** [comment]
Hiya, 

Thanks to your insight, I built it into an option. So, your feature request has been added to this [PR](https://github.com/SickGear/SickGear/pull/1200) - it will not be backported because that PR has many changes involving subtitles and these will all be merged into develop/master anyway. I'm letting you know now so that you may go in and confirm that the feature is working for you, if there is a related issue, then we can address it now :)

* Add "Enforce media hash match" to config/Subtitles Plugin/Opensubtitles for accurate subs if enabled, but if disabled, search failures will fallback to use less reliable subtitle results

<img src="https://i.vgy.me/NaqYAv.png">

**Comment by JackDandy** [comment]
This feature request is now available in the develop branch.

* Add "Enforce media hash match" to config/Subtitles Plugin/Opensubtitles for accurate subs if enabled, but if disabled, search failures will fallback to use less reliable subtitle results

<img src="https://i.vgy.me/3B9RoE.png">

**Comment by JackDandy** [comment]
Available in master [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.0).
