### ISSUE TITLE
Traceback error while downloading subtitles / Opensubtitles credential missing?

### ISSUE THREAD

**Issue by baronebirra82** [SickGear/SickGear#1216]
#### Branch version commit hash: c3682d2

Expectation | Result
------------ | -------------
Subtitles succesfully downloaded both in italian and english | only downloaded them in english with an error (see below)

**Steps to reproduce:**
*1)* Activate every subtitle provider
*2)* Put English and Italian languages
...

**Additional notes:**
Opensubtitles requires username and password. In other versions of Sick softwares there is an option to put them: where can i put them? could it be the reason why i don't get italian subtitles? Opensubtitles is a very realiable source for every language.

**Error details:**
2019-11-27 03:51:01 ERROR    FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
 1)   File "/share/CACHEDEV1_DATA/.qpkg/SickGear/SickGear/sickbeard/tv.py", line 1728, in downloadSubtitles
 2)     multi=True, cache_dir=sickbeard.CACHE_DIR)
 3)   File "/share/CACHEDEV1_DATA/.qpkg/SickGear/SickGear/lib/subliminal/api.py", line 95, in download_subtitles
 4)     subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
 5)   File "/share/CACHEDEV1_DATA/.qpkg/SickGear/SickGear/lib/subliminal/api.py", line 62, in list_subtitles
 6)     service_instance.terminate()
 7)   File "/share/CACHEDEV1_DATA/.qpkg/SickGear/SickGear/lib/subliminal/services/opensubtitles.py", line 103, in terminate
 8)     raise ServiceError(str(e))
 9) ServiceError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Backend fetch failed>

**Comment by JackDandy** [comment]
OpenSubtitles does not actually **require** a username and pw, it is an optional feature.

That said, username and password has been added to a feature branch that is due for release soon. Also, please note that there are no plans to support languages other than English - this has always been the case for SG and is stated in the FAQ.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by baronebirra82** [comment]
Sorry, my bad. I will try to be more specific next time.

Thanks anyway
