### ISSUE TITLE
'ascii' codec can't encode character u'\u2013' in position 99: ordinal not in range(128)

### ISSUE THREAD

**Issue by gdevenyi** [SickGear/SickGear#1220]
#### Branch: The name of the branch (e.g. master or develop)
develop
#### Branch version commit hash: (See the About page)
a53a5c2

Expectation | Result
------------ | -------------
Importing does not halt with encoding error | Importing halts with encoding error

**Steps to reproduce:**
*1)* Try to process a file containing en-dash: https://www.fileformat.info/info/unicode/char/2013/index.htm
...

```
Error
'ascii' codec can't encode character u'\u2013' in position 99: ordinal not in range(128)

Traceback
Traceback (most recent call last):
File "/opt/SickGear/lib/tornado/web.py", line 1592, in _execute result = yield result
File "/opt/SickGear/lib/tornado/gen.py", line 1133, in run value = future.result()
File "/opt/SickGear/lib/tornado/concurrent.py", line 261, in result raise_exc_info(self._exc_info)
File "/opt/SickGear/lib/tornado/gen.py", line 307, in wrapper result = func(*args, **kwargs)
File "/opt/SickGear/sickbeard/webserve.py", line 700, in get result = method(**kwargss)
File "/opt/SickGear/sickbeard/webserve.py", line 3046, in processEpisode skip_failure_processing=skip_failure_processing)
File "/opt/SickGear/sickbeard/processTV.py", line 986, in processDir dir_name, nzb_name, process_method, force, force_replace, failed, type, cleanup, showObj)
File "/opt/SickGear/sickbeard/processTV.py", line 416, in process_dir self.check_video_filenames(walk_dir, video_pick)))
File "/opt/SickGear/sickbeard/processTV.py", line 900, in _process_media file_success = processor.process()
File "/opt/SickGear/sickbeard/postProcessor.py", line 1068, in process ep_obj.createMetaFiles()
File "/opt/SickGear/sickbeard/tv.py", line 2234, in createMetaFiles self.createNFO()
File "/opt/SickGear/sickbeard/tv.py", line 2245, in createNFO result = cur_provider.create_episode_metadata(self) or result
File "/opt/SickGear/sickbeard/metadata/generic.py", line 311, in create_episode_metadata result = self.write_ep_file(ep_obj)
File "/opt/SickGear/sickbeard/metadata/generic.py", line 506, in write_ep_file return helpers.write_file(nfo_file_path, data, xmltree=True, utf8=True)
File "/opt/SickGear/sickbeard/helpers.py", line 1749, in write_file with io.FileIO(filepath, 'wb') as fh:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 99: ordinal not in range(128)

Request Info
body: type=manual&_xsrf=2%7C4f7bb799%7C505d1c5ca20a05011c901e1df5f1f2e1%7C1576197721&dir=<redacted>%2FSeasons+10-31&process_method=hardlink
files: {}
protocol: http
connection:
body_arguments: {'_xsrf': ['2|4f7bb799|505d1c5ca20a05011c901e1df5f1f2e1|1576197721'], 'type': ['manual'], 'dir': ['<redacted>/Seasons 10-31'], 'process_method': ['hardlink']}
uri: /home/postprocess/processEpisode
query_arguments: {}
_start_time: 1576197736.23
headers: Origin: http://<redacted>:8081 Content-Length: 144 Accept-Language: en-CA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7 Accept-Encoding: gzip, deflate Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3 Upgrade-Insecure-Requests: 1 Dnt: 1 Host: <redacted>:8081 Referer: http://<redacted>:8081/home/postprocess/ Cache-Control: max-age=0 Cookie: snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; advanced_toggle_checked=1; wanted_view=thumb; manage_view=thumb; _xsrf=2|99df41b4|86f9ea7174aef32cca34e830235504cc|1576197721 User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36 Content-Type: application/x-www-form-urlencoded
host: <redacted>:8081
version: HTTP/1.1
server_connection:
host_name: <redacted>
_finish_time: None
query:
arguments: {'_xsrf': ['2|4f7bb799|505d1c5ca20a05011c901e1df5f1f2e1|1576197721'], 'type': ['manual'], 'dir': ['<redacted>Seasons 10-31'], 'process_method': ['hardlink']}
path: /home/postprocess/processEpisode
_cookies: Set-Cookie: _xsrf=2|99df41b4|86f9ea7174aef32cca34e830235504cc|1576197721 Set-Cookie: advanced_toggle_checked=1 Set-Cookie: blu_ray_com_new_releases_view=thumb Set-Cookie: imdb_box_office_view=thumb Set-Cookie: imdb_movies_in_theaters_view=thumb Set-Cookie: imdb_top_250_movies_view=thumb Set-Cookie: late_view=list Set-Cookie: manage_view=thumb Set-Cookie: snatched_view=list Set-Cookie: soon_view=thumb Set-Cookie: suggest_view=thumb Set-Cookie: wanted_view=thumb
method: POST
remote_ip: 192.168.1.222
```

**Comment by JackDandy** [comment]
Hi,

Please process proper video file(s) and not text files.  

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
Hi,

you have redacted the most important info, 
1) what was the name of the video you were trying to import
2) what do you have set for your postproviders/meta  

looking at the log it seems like an import of meta data is causing issue, so some tvdb/other data is perhaps corrupt.

**Comment by JackDandy** [comment]
Hi,

you have redacted the most important info, 
1) what was the name of the video you were trying to import
2) what do you have set for your postproviders/meta  

looking at the log it seems like an import of meta data is causing issue, so some tvdb/other data is perhaps corrupt.

**Comment by JackDandy** [comment]
Hi,
 
1) What was the name of the video you were trying to import?
2) What do you have set for your config/Media(Post) process/Metadata ?

Looking at the log it seems like an import of meta data is causing issue, so some tvdb/other data is perhaps corrupt.

Also, the folder name `Seasons 10-31` is not standard to sg, so i'm not sure what data exists in there that could be corrupt. So you need to isolate the actual file so that we can have a copy and then I can replicate your edge case issue to fix it.

**Comment by gdevenyi** [comment]
1) the content of magnet:?xt=urn:btih:831b8bab0c4219605e76ed8c1a121df692544685&dn=Mister+Rogers+Neighborhood+Seasons+10-31&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.ccc.de%3A80

I'm not sure exactly which file yet because the exception doesn't propogate the full details.
2) will get back to you

**Comment by JackDandy** [comment]
> the content of...

Okay, you sent a magnet to a number of files spanning 21 seasons. Placing just one of those files in a folder and then using the import menu item, will reproduce the error you found. So the question is, which file? (perhaps do it in batches of 10 files in order to isolate the bad file in this pack)

**Comment by JackDandy** [comment]
First, to perhaps save us time, I need to make sure you are not making a user mistake. You are not trying to use the menu/Tools/Import function to import an unprocessed download are you? The Import item is for importing a show that was previously processed. For a new download, you use the Manage/Process Media, and of course you will have added the show already. If we are all good, and you are using the correct menu item, then...

> the content of...

Okay, you sent a magnet to a number of files spanning 21 seasons. Placing just one of those files in a folder and then using the process media function, will reproduce the error you found. So the question is, which file? (perhaps do it in batches of 10 files in order to isolate the bad file in this pack) -- with this answer, the answer for q2 will also be relevant.

**Comment by gdevenyi** [comment]
> For a new download, you use the Manage/Process Media

Yes, doing that thanks.

> Okay, you sent a magnet to a number of files spanning 21 seasons. Placing just one of those files in a folder and then using the process media function, will reproduce the error you found. So the question is, which file?

Agreed, didn't have the time when the bug triggered go do the manual work, so I started with reporting, in case its obvious to you in the code. I will batch reprocess go find the culprit.

**Comment by gdevenyi** [comment]
"Season 13" triggered the error, likely episode 01, it appears the title contains an en-dash.
```
"Friendship: Sharing Can Be Hard – Even for Friends"
								 ^en-dash UTF-8 character.
```
The video file is properly named, and it appears the UTF-8 has been stripped as "ls -b" does not escape the "-" character.

There is no NFO file for this episode.

https://www.thetvdb.com/series/mister-rogers-neighborhood/episodes/257058

**Comment by JackDandy** [comment]
So, that filename is...
  
`Mister Rogers' Neighborhood - S13E01 - Friendship Sharing Can Be Hard – Even for Friends.mp4`

That "hyphen" between "hard" and "Even" is a utf8 char hyphen. 

Now, as SG obviously works with utf8 at OS filesystem level, the error indicates that you are using a non Windows OS **and** that your `locale` for that OS is not set up for utf8. Once you fix that, this error should not exist.

Proof of successfully processed file, on Windows env...  
  
<pre>
Checking folder... <base_path>
Processing folder... <base_path>
Processing sub dir: Mister Rogers Neighborhood Season 13
Processing... Mister Rogers' Neighborhood - S13E01 - Friendship Sharing Can Be Hard – Even for Friends.mp4
Parsed Mister Rogers' Neighborhood - S13E1 [ABD: False] [ANIME: False] [whichReg: ['standard']]
.. from Mister Rogers' Neighborhood - S13E01 - Friendship Sharing Can Be Hard – Even for Friends.mp4
Retrieving episode object for 13x1
Found "Unknown" quality parsed from the file name Mister Rogers' Neighborhood - S13E01 - Friendship Sharing Can Be Hard – Even for Friends.mp4
Found "Unknown" quality parsed from the folder name Mister Rogers Neighborhood Season 13
Using guessed "SD TV" quality from the file name Mister Rogers' Neighborhood - S13E01 - Friendship Sharing Can Be Hard – Even for Friends.mp4
Existing episode status is not downloaded/archived, marking it safe to replace
Destination folder for this episode is D:\_Video\tv\Mister Rogers' Neighborhood\Season 13
Copied file from <base_path>\Mister Rogers Neighborhood Season 13\Mister Rogers' Neighborhood - S13E01 - Friendship Sharing Can Be Hard – Even for Friends.mp4
.. to D:\_Video\tv\Mister Rogers' Neighborhood\Season 13\Mister.Rogers.Neighborhood.s13e01.Friendship.Sharing.Can.Be.Hard.–.Even.for.Friends.SD.TV.mp4
Successfully processed Mister Rogers' Neighborhood - S13E01 - Friendship Sharing Can Be Hard – Even for Friends.mp4
-----------------------
Successfully processed.
</pre>
  
There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by gdevenyi** [comment]
Nope.

```
$ locale
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=
```

**Comment by gdevenyi** [comment]
The error stream posted looks to me like the error is thrown trying to encode utf8 into the NFO file being generated. The video file is properly copied and named.

``` line 506, in write_ep_file return helpers.write_file(nfo_file_path, data, xmltree=True, utf8=True)
> File "/opt/SickGear/sickbeard/helpers.py", line 1749, in write_file with io.FileIO(filepath, 'wb') as fh:
```

**Comment by JackDandy** [comment]
Again, your `locale` is wrong, try...

`env LANG=C.UTF-8 LC_ALL=C.UTF-8`

**Comment by gdevenyi** [comment]
Even more particularly it looks like the file name handling for the NFO generating, rather than the encoding inside the NFO, as I have other NFO files with utf8 properly in them.

**Comment by JackDandy** [comment]
Again, your `locale` is wrong, try...

`env LANG=C.UTF-8 LC_ALL=C.UTF-8`

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.20.13)

**Comment by gdevenyi** [comment]
Cheers. Is there are mechanism to force the re-generation of all NFO files? It looks like the video importation worked as did the insertion in the database but the NFO bailed out, so failing files (of which I may have more?) are missing.

**Comment by JackDandy** [comment]
If you take exactly the same steps that you determined created the issue, with the isolated `S13E01` media file - can you confirm that the .nfo metadata file is generated for that episode.

**Comment by gdevenyi** [comment]
Okay, yes I can do that in this case, but I guess this is a more general request then. I suspect there may be other instances of this which have arised from automated processing which I didn't notice, is there a method to trigger re-generation across all files? Similar to the "missing subtitles" feature, but for metadata files? If not, I guess this is a feature request.

**Comment by JackDandy** [comment]
try;
1) menu Manage/Bulk Change 
2) use column Rescan 
3) click [Submit]
