### ISSUE TITLE
progressbar not showing up

### ISSUE THREAD

**Issue by b0red** [SickGear/SickGear#1233]
#### Branch version commit hash: COMMIT: b2a5bab @ 0.21.1

Python Version: | 2.7.17 (default, Dec 27 2019, 03:34:56) [GCC 9.2.0]

Expectation | Result
To see how many shows of a series has been downloaded | Nothing is showing up. See imgur link

**Steps to reproduce:**
*1)* Start / open webpage of SickGear on your machine.
...
[See imgur link](https://imgur.com/a/WVmDb6X)

Additional notes:
For example, any relevant config settings that may be help us replicate the reported issue

Targeting your info so that the issue can be reproduced is the single fastest way to get it resolved

**Comment by JackDandy** [comment]
By design, that stat is not available on that particular layout.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by b0red** [comment]
Well I saw it before the last update, so it seems strange. In what layout is it supposed to show? I'm confused. :) :/

**Comment by JackDandy** [comment]
Because the last update did nothing to remove UI elements, I assumed your view was schedule day-by-day. The screenshot you gave shows no context so I cannot say for sure. Contrast your screenshot with the following from FF browser with layout context to help see what is going on ...
<a name=""><img src="https://i.vgy.me/4Hs28X.png"></a>
