### ISSUE TITLE
Multi-episode files only produce nfo-files for one of the episodes

### ISSUE THREAD

**Issue by aMvEL** [SickGear/SickGear#1238]
#### Branch version commit hash: (See the About page)

BRANCH: develop / COMMIT: d8cdb1f @ 0.22.0

Expectation | Result
nfo file produced with multi-epsiode video-file (S01E01E02E03) should contain <episodedetails> for all episodes | the nfo only contains the <episodedetails> for the last episode (S01E03). It is possible the nfo-file gets overwritten per episode.

**Steps to reproduce:**
*1)*  Import a previously added, or already organized tv-series (import existing show)
*2)*  Let it fetch metadata and check nfo-file afterwards.

uncut logfile from a fresh install.
https://gist.github.com/aMvEL/63d7eda2bd4b5a4a5d64601317ad2406

Additional notes:
It is kind of a weird one. Because if you take the multi-episode file and run it through Manage ->Process media, it generates a correct nfo-file with info for all episodes. But it seems to re-generate the wrong nfo during the next show update loop.

**Comment by JackDandy** [comment]
Hi,

From your log, two things are happening, an upgrade, followed by maybe some other action from you. 

Does the issue you report happen under normal operation of importing previously added show or is this something to do with upgrading ?

**Comment by aMvEL** [comment]
It is weird that the logs would show anything related to upgrading. The log should only contain me importing a folder with the show. Nothing else. 

In any case the issue is not related to upgrading, I never use that function.

It happens in 3 places for me. When importing a show, when force updating a show and during regular daily show updates.
If I however take that file and process it manually, force replacing itself, it correctly creates a multi-episode nfo.

**Comment by JackDandy** [comment]
@aMvEL Maybe take look at your stars :)

**Comment by JackDandy** [comment]
@aMvel

I imported show with same episode named as yours, and the results in the image below, am i missing something as i do not understand what you are reporting?

<img src="https://i.vgy.me/Vqqiho.png">

**Comment by aMvEL** [comment]
Weird. So it's just here that it's not working.... Then I can't explain it. It just somehow does not work properly on my systems.

**Comment by JackDandy** [comment]
> It just somehow does not work properly on my systems

After importing the show, what are the contents (use gist) of the `.nfo` file ...  
`D:\TVTEMP\Animaniacs\Season 5\Animaniacs.S05E01E02E03.Moosage.in.a.Bottle.-.Back.in.Style.-.Bones.in.the.Body.NTSC.DVDRip.DD5.1.x264-AWOL.nfo`

Also, do you have a media file in that Season 5 folder called, `s05e02` or `s05e03` maybe ?

**Comment by JackDandy** [comment]
Ahh wait, you said the step wrong...

> It happens in 3 places for me. When importing a show...

That actually works, BUT if i then do a "force update` the file is overwritten with data for ONLY S05e03, can you confirm this.

**Comment by aMvEL** [comment]
It's weird actually.. I can confirm what you say that the force update overwrites it.

But for me it also happens when importing....

**Comment by JackDandy** [comment]
> also happens when importing

@aMvEL By any chance, do you also have media files for `s05e02` and/or `s05e03` or do you just have the single `s05e01e02e03` media file ?

**Comment by aMvEL** [comment]
I only have the single S05E01E02E03 file yes.

**Comment by JackDandy** [comment]
It occurred to me that the xml root tag of `xbmcmultiepisode` is still in use since SickBeard, so I looked to the xbmc repo for the new replacement and found an issue `16506` filed Aug 2019 that indicates that a multiple episode details tag support may not even be used at all (that is IF Kodi has remove the parsing of root tag `xbmcmultiepisode` - could be the issue thread OP didn't know it exists). 

So yeah, it would be useful to prove there is a reason to fix this, because the multi `nfo` file xml data could be ignored by Kodi or worse, see later.  

If **you** get a correct multi nfo file like you can, then can you prove/confirm that it is actually being used? 

I say this because last weekend, joy was had with Kodi and these `.nfo` files learning that it can be, umm, fussy on some configurations. A seemingly innocuous change to an xml `.nfo` file resulted in Kodi crashing when doing a library update on particular Linux configurations.

So given a simple xml text fail can have such a negative result, I am very hesitant, to the point where I do not want to change things with these files unless it can be proven a change actually has a positive outcome.

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.5)

Thanks for the report.
