### ISSUE TITLE
Set any show to archived

### ISSUE THREAD

**Issue by herkalurk** [SickGear/SickGear#1239]
#### Branch version: 0.21.5

Expectation | Result
------------ | -------------
When I mark an episode as archived it will change it's status to archived | Some episodes which may not have been downloaded, or episodes which are currently listed as snatched do not change and remain as ignored, skipped, or snatched

I use Sickgear to track all of my tv shows so I can keep up to date when they're going to air, etc.  I have cable and don't use Sickgear to find the episodes so some of the TV shows are always paused and I want to clean up the episode lists to show that a season may be complete.  If there isn't a file for a particular episode, Sickgear won't change the show status to anything that would indicate it is complete.  I would appreciate being able to override that.

**Comment by JackDandy** [comment]
Hello,

I understand clearly what you are saying. 

The purpose of status `Archived` is to indicate that files that did exist on a drive have been archived offline and/or no longer exist. Only episodes with status `Downloaded` can be changed to status `Archived` and this is by design. If you want to override this intentional behavior, then you may first set status to `Downloaded`, and then to `Archived` - yes, a two step process for different use cases/reasons.

**Comment by JackDandy** [comment]
Hello,

I understand clearly what you are saying. 

> Sickgear won't change the show status to anything that would indicate it is complete

This is invalid. By design, status `Downloaded` **is** the status for complete.

The purpose of status `Archived` is to indicate that files that did exist on a drive have been archived offline and/or no longer exist. Only episodes with status `Downloaded` can be changed to status `Archived` and this is by design. 

If you want to override the designed behavior, then you may first set status to `Downloaded`, and then to `Archived` - a two step process for different use cases/reasons than yours.
