### ISSUE TITLE
Postprocessor not processing subdirs of show root

### ISSUE THREAD

**Issue by fritz-k** [SickGear/SickGear#1247]
Hi,

I store unprocessed episodes in a directory "_temp" which resides under the root dir which is shared via smb. This way episodes that don't get recognized properly still reside in the share and can be viewed if desired. Commit c44d5805558dcad779fbc70572bbc720afd17b65 prevents me from continuing to do so by not processing any directories inside the root dirs.

Is this strictly necessary or to prevent weird behavior if misconfigured? In the latter case, I'd like to get the old behavior back, either via a setting or by switching to warning the user in case he adds a root dir that is an ancestor of any processing dirs or a processing dir that is a descendant of any root dir.

Cheers,
Simon

**Comment by JackDandy** [comment]
> Is this strictly necessary or to prevent weird behavior if misconfigured? 

Yes, this is **absolutely strictly necessary**, and why it was added into code.

**Comment by JackDandy** [comment]
Hi Simon,

> Is this strictly necessary or to prevent weird behavior if misconfigured? 

Yes, this is **absolutely strictly necessary**, and why it was added into code. 

> episodes that don't get recognized properly

This here is your issue.  Files named properly will be **recognized** and will post process fine. Instead, you are fighting against what makes the system stable by trying to force badly named files into it, and just in case, file naming is **not** the reason that code protection exists.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
JD

**Comment by fritz-k** [comment]
Hi JD,

thanks for the quick reply!

That's too bad. It probably won't change anything, but I think I didn't make myself quite clear:

>
> > episodes that don't get recognized properly
> 
> This here is your issue. Files named properly will be **recognized** and will post process fine. Instead, you are fighting against what makes the system stable by trying to force badly named files into it, and just in case, file naming is **not** the reason that code protection exists.

The files are downloaded externally, mostly triggered by sickgear, but not exclusively. Most of them are named properly and get recognized by sickgear, very few aren't and it might be a while until someone looks after them, so it's quite convenient if they reside on the shared volume for people to watch despite not being sorted into the right folder.

My layout is this:
```
root-dir (shared via smb)
└─── show1 (managed by sickgear)
└─── show2 (managed by sickgear)
└─── ...
└─── showX (not managed by sickgear)
└─── showY (not managed by sickgear)
└─── _temp (new files are hardlinked in here, processed by sickgear and moved to the
            proper show dir; no permanent dir for any show)
```
Up until now sickgear didn't care about the shows not managed by it and I don't see how `_temp` - not being a show dir - necessarily has to confuse sickgear.

I believe this to be a somewhat rational setup given the circumstances. With this "feature" removed I'd have to a) not share the processing dir and look through it more regularly or b) set each show-dir as root-dir, which would be quite a hassle since sickgear tracks quite a lot of shows.

Cheers,
Simon

**Comment by Prinz23** [comment]
If you want to keep that:

Why don't you create the _temp dir outside of root dir, set this one in sg as processing dir, then link the _temp folder inside the root dir so your share still has access to it?

**Comment by JackDandy** [comment]
Hi Simon,

> I don't see how _temp - not being a show dir - necessarily has to confuse sickgear

I agree. And it doesn't.   

In fact, there are no such issues **until** a PEBCAK manually selects a parent folder on for example `_temp` during a media process with `Move` and `delete left over files` selected, and then tries to blame SG for lost files due to an inability to read red warnings that state never to use such a configuration.  So here we are, with logic to protect against that kind of user barf.

JD

**Comment by fritz-k** [comment]
> Why don't you create the _temp dir outside of root dir, set this one in sg as processing dir, then link the _temp folder inside the root dir so your share still has access to it?

That's probably the best solution, I'll have to look up security implications of symlinks in smb shares first though.

> with Move and delete left over files selected

I didn't notice the `delete left over files` option. With this combo I completely understand why you want to make sure not to process anything inside the root dir.

Thanks for taking the time to explain and work on this great tool :)

Cheers,
Simon
