### ISSUE TITLE
Latest autoupdate on SL7.7 doesn't launch.

### ISSUE THREAD

**Issue by jmp242** [SickGear/SickGear#1260]
#### Branch version commit hash: 315b817

Expectation | Result
------------ | -------------
Update Sickgear, sickgear launches. | Sickgear will not restart, gives error

**Steps to reproduce:**
*1)* Scientific Linux 7.7. (basically CENTOS7.7.) Use a pyenv of 2.7.10.
*2)* Run built in updater, or download and extract Zip file, copy in existing database etc.
*3)* Try and run sickgear at CLI.

Either a link to gist (best as they are easily deleted) or log text wrapped in "pre" tags

https://gist.github.com/jmp242/701a0dd7c8712ccb95578c98b262ee6b

**Comment by JackDandy** [comment]
Hi,

You have managed to mangle the SickGear installation files, probably by using zip files to update instead of the proper way.

The reason this is known is because...
1) `/mnt/DataDrive/sickbeardlinux/SickGear-master/sickbeard/encodingKludge.py` has not existed for a long time. These days, there is ... `SickGear-master/lib/encodingKludge.py`
2) the error message you report is from an old module, and no longer exists.

I strongly recommend you rename your old installation folder `something_old` and use `git` to install into a new fresh folder in order to get an installation that properly updates itself via `git` (in path) instead of downloading and extracting zip files.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
Hi,

You have managed to mangle the SickGear installation files, probably by using zip files to update instead of the proper way.

The reason this is known is because...
1) `/mnt/DataDrive/sickbeardlinux/SickGear-master/sickbeard/encodingKludge.py` has not existed for a long time. These days, there is ... `SickGear-master/lib/encodingKludge.py`
2) the error message you report is from an old module, and no longer exists.

I strongly recommend you rename your old installation folder `something_old` and use `git` to install into a new fresh folder in order to get an installation that properly updates itself via `git` (in path) instead of downloading and extracting zip files.

If you must only download zip files, then you **must** backup the db's + ini and delete the SG folder contents before extracting the new zip ... then readd the db's + ini (unless you use a extrernal data dir for db and ini files and use the `--datadir` startup param) otherwise you will get errors all the time with removed or moved files.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by jmp242** [comment]
This worked. I think what happened is years ago I installed using the zip method, and the used auto update 100 times or whatever. No idea why the last auto update broke, but I migrated to the production git checkout like you recommend and hopefully auto update from the web ui will work for a few more years.

Thanks,hope this helps someone else later.

________________________________

**Comment by JackDandy** [comment]
I also posted this [here](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#bad-install) to help others. This thread will be removed.

**Comment by JackDandy** [comment]
I also posted this [here](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#bad-install) to help others. This thread will be removed. The last update broke because you had a corrupt installation and was living on borrowed time.
