### ISSUE TITLE
Kod

### ISSUE THREAD

**Issue by daktak** [SickGear/SickGear#1269]
#### da77a94

Expectation | Result
------------ | -------------
install watched plugin from repo | failed

**Steps to reproduce:**
*1)* Add source 
*2)* Install addon

I believe this is due to having web_root set to a sub-directory (allowing me to use nginx to reverse proxy along with other programs)

Also the watched addon has host / port settings. I'm unsure if it'll connect when a web_root is set?

**Comment by JackDandy** [comment]
Please follow exactly the instructions for installation, using reverse proxies were never designed for a connection between Kodi and SG as the two communicate directly as a trusted link, therefore, a reverse proxy is not required.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by daktak** [comment]
Thanks, I edited line 292 of service.sickgear.watchedstate.updater/service.py to the below,
perhaps a new config variable needed for web_root?
url = 'http://%s:%s/sickgear/update-watched-state-kodi/' % (

**Comment by JackDandy** [comment]
If you create a full PR, including config for the Kodi UI plugin side of things, then that can be merged.
