### ISSUE TITLE
Git executable path setting missing

### ISSUE THREAD

**Issue by KeenIIDX** [SickGear/SickGear#1294]
#### Branch version commit hash: About page says "BRANCH: UNKNOWN @ py2.7.18 / COMMIT: UNKNOWN @ 0.21.37"

Expectation | Result
------------ | -------------
config/general/advanced should have a Git executable path setting | That config item is not present.

**Steps to reproduce:**
*1)* Did an [install](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B1%5D-Windows), imported my Sick-beard config and db files.
*2)* Go to Config-> General-> Advanced.
*3)* No Git executable path setting is present.

Additional notes:
Installed under C:\Program Files (x86)\Sick-Gear
Data dir is C:\Program Files (x86)\Sick-Gear\data
Errors in logs:
<pre>
2020-07-04 13:25:52 TORNADO :: No git specified, cannot use git commands
2020-07-04 13:22:45 MAIN :: Failed: "C:\Program Files (x86)\Git\bin\git.exe" version returned: The system cannot find the path specified.
2020-07-04 13:22:45 MAIN :: Failed: "c:\program files (x86)\git\bin\git.exe" version returned: The system cannot find the path specified.
2020-07-04 13:22:45 MAIN :: No git specified, cannot use git commands
2020-07-04 13:22:45 CHECKVERSION :: No git specified, cannot use git commands
2020-07-04 13:22:45 CHECKVERSION :: No git specified, cannot use git commands
</pre>

Note: Git is at C:\Program Files\Git\bin\git.exe  Do I need to install a 32-bit Git?

**Comment by JackDandy** [comment]
>  Do I need to install a 32-bit Git?

Nope, simply install git in such a way that the custom option to include git in the path is enabled, alternatively, if you don't wish to do that, then you can add the path in settings general/advanced, the choice is yours.

**Comment by JackDandy** [comment]
>  Do I need to install a 32-bit Git?

Nope, simply install git in such a way that the installed includes `git` in the path - this is your issue, no git found.

Also, unless you are using a docker env, then you should be able to see and set...

<img src="https://i.vgy.me/CBL4Y3.png"> 

but you reported that you cannot so your `git` install is borked as SG cannot determine a commit hash.  SG sounds like it is installed fine, but you should fix your `git` installation so that you can receive important updates.

**Comment by JackDandy** [comment]
>  Do I need to install a 32-bit Git?

Nope, simply install git in such a way that the installed includes `git` in the path - this is your issue, no git found.

Also, unless you are using a docker env, then you should be able to see and set...

<img src="https://i.vgy.me/CBL4Y3.png"> 

but you reported that you cannot so your `git` install is borked as SG cannot determine a commit hash.  SG sounds like it is installed fine, but you should fix your `git` installation so that you can receive important updates.

**Comment by KeenIIDX** [comment]
Found the git_path in my config.ini was pointed to that bad path.  Clearing it fixed the issue.  The version is now populated on the About page, the Git executable path setting is now present on Advanced tab.

**Comment by JackDandy** [comment]
Thanks for the feedback, we may be able to stop this occurring for future migrations, now that we know.

**Comment by JackDandy** [comment]
Added alternative locations for `git.exe` on Windows with a log warning to user.

Thanks for the feedback.
