### ISSUE TITLE
WARNING  TORNADO.GEN :: 403 POST /errorlogs/viewlog/ (192.168.1.26): '_xsrf' argument missing from POST

### ISSUE THREAD

**Issue by galant56k** [SickGear/SickGear#1296]
Master
windows 10 pro x64
python 3.8

this error is comming every second.
also dont know where is getting this ip address from (192.168.1.26) this is that ip address of another pc in my network not related to sickgear pc

[sickgear log.zip](https://github.com/SickGear/SickGear/files/4929611/sickgear.log.zip)
![Capture](https://user-images.githubusercontent.com/4738715/87633153-322f7880-c77e-11ea-9235-6aad2efd9a62.JPG)

**Comment by JackDandy** [comment]
SickGear added the `_xsrf` argument over 2 years ago in April 2018 for increased security. That error output looks like the running `autoProcessTV` _or third party processing_ script and its config is very outdated. Follow [here](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B80%5D-Extras) for help setting the script up.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.
