### ISSUE TITLE
Feature Request: Referred words list for searches

### ISSUE THREAD

**Issue by boredazfcuk** [SickGear/SickGear#1309]
Hi,

I'm just throwing this out these as a possible area for improvement somewhere down the line.

Currently **Ignored Words** and **Required Words** are configurable, but I was wondering if it would be possible to implement a **Preferred Words** system too?

That way, I could set a preferred words of DDP5.1 and/or DTS and it would select those rather than releases with AC3 or AAC in the name. If no DDP5.1 or DTS releases existed, it would still download the AC3/AAC releases.

I'd also like to prefer x265 over x264 so it would be handy for this scenario too.

This is probably going to be a bit more complex than the current system, which simply eliminates potential downloads on an inclusive or exclusive basis. A **Preferred Words** system would probably need to rank the releases so the one with the most preferred words would be selected.

I'm not sure how easy it would be to include this, but presumably there must be some sort of selection criteria in the background which chooses the most appropriate release when multiple exact matches are found (based on name, quality, etc.)?

Thanks.

**Comment by potestus** [comment]
I would use this for exactly the same situation x265.

**Comment by PowerCoder** [comment]
Recently, with the instability of some of the more well-known media providers, the search can come up with some of the strangest and sometimes low-quality episodes and then stop searching unless it meets the Upgrade requirement.

I would love to be able to give it these preferred terms in the desired quality so that it will still discover the low-quality version (the in case of emergency one) but it will upgrade to another one within the same class/category if that one has the preferred word(s) in it.

To use the above example, if the desired quality is SD it might find a 480p x264. But if I am able to set something like "x265" as preferred it will "upgrade" it to a 480p x265 when it finds one. Or if it finds a release by the NEVERINSYNC group it would "upgrade" to the "ALWAYSWORKS" group even if the aspect ratio/quality is listed as identical.

My guess it it would require more upgrade-to loops and searches. And the preferred search terms would be parsed in order. Lower down the list means it "upgrades" the ones higher on the list.

Alternatively, you could do away with the current desired and upgrade to category buttons and replace them with pre-defined but editable profiles. I assume they already are collection of regex search terms in the code, now you would simply make those visible in the interface and allow users to edit the categories. So if right now "SD" means anything which does not have "720p" or higher in its search terms, people could add "x265" to that definition to refine it. Combine that with the parsed-in-order list and they could control what upgrades to what.

The big downside is more searches I'm guessing (you might want to limit the amount of items in the upgrade list). Oh, and definitely put this functionality under a checkbox called "Advanced Option - No Support If You Break It!"

Just throwing some ideas around, I'm a scripter, not a coder, so I could be completely wrong in how this works.
