### ISSUE TITLE
Error when trying to import shows

### ISSUE THREAD

**Issue by tenpin784** [SickGear/SickGear#1310]
BRANCH: master @ py2.7.13 / COMMIT: 0f35f31 @ 0.22.0

I am trying to import a show that is already in the end media location. Previously I would see any shows listed that had folders and data but were not in SickGear. 

Now, nothing is listed on the page, and it constantly says "scanning parent folders". Looking at the log, it throws the following errors:

<pre>
HTTPServerRequest(protocol='http', host='192.168.10.1:8083', method='GET', uri='/add-shows/mass-add-table?root_dir=%2Fexport%2Fmediaserver%2Ftv', version='HTTP/1.1', remote_ip='192.168.10.21')
Traceback (most recent call last):
  File "/opt/SickGear/app/lib/tornado_py2/web.py", line 1592, in _execute
    result = yield result
  File "/opt/SickGear/app/lib/tornado_py2/gen.py", line 1133, in run
    value = future.result()
  File "/opt/SickGear/app/lib/tornado_py2/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/opt/SickGear/app/lib/tornado_py2/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/SickGear/app/sickbeard/webserve.py", line 833, in get
    yield self.route_method(route, use_404=True)
  File "/opt/SickGear/app/lib/tornado_py2/gen.py", line 1133, in run
    value = future.result()
  File "/opt/SickGear/app/lib/tornado_py2/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/opt/SickGear/app/lib/tornado_py2/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/SickGear/app/sickbeard/webserve.py", line 223, in route_method
    result = yield self.async_call(method, request_kwargs)  # method(**request_kwargs)
  File "/opt/SickGear/app/lib/tornado_py2/gen.py", line 1133, in run
    value = future.result()
  File "/opt/SickGear/app/lib/tornado_py2/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
Exception: Traceback (most recent call last):<br>  File "/opt/SickGear/app/sickbeard/webserve.py", line 232, in async_call<br>    return function(**kw)<br>  File "/opt/SickGear/app/sickbeard/webserve.py", line 3695, in mass_add_table<br>    (sn, idx, pid) = helpers.search_infosrc_for_show_id(show_name, tvid, prodid)<br>  File "/opt/SickGear/app/sickbeard/helpers.py", line 301, in search_infosrc_for_show_id<br>    tvinfo_config = sickbeard.TVInfoAPI(_tvid).api_params.copy()<br>  File "/opt/SickGear/app/sickbeard/indexers/indexer_api.py", line 34, in __init__<br>    self.tvid = int(tvid) if tvid else None<br>TypeError: int() argument must be a string or a number, not 'dict'<br></pre>

**Steps to reproduce:**
*1)* Click on menu item with a wrench and screwdriver
*2)* Click on Import exisiting shows
*3)* Errors seen in the sickgear.log file

**Comment by JackDandy** [comment]
Hello, 

I have run two tests with your steps and cannot reproduce this issue.

This leads be to think that there is corruption on your filesystem outside of SickGear that is causing this.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
Hello, 

I have run two tests with your steps and cannot reproduce this issue.

This leads be to think that there is corruption on the filesystem of your `end media location` that is causing this.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
Hello, 

I have run two tests with your steps and cannot reproduce this issue.

This leads be to think that there is corruption on the filesystem of your `end media location` that is causing this.

You can try to run the steps again, but from a test location and place only one show in there as test 1. Then, add some more shows at that test location as test 2. Then repeat 2 until you isolate the show that is caused the issue. Then send us that detail.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
Hello, 

I have run **two** tests with your steps and cannot reproduce this issue.

This leads be to think that there is corruption in a .nfo file that is causing this. You do not mention if in the logs there is a report of such a thing, but it can be the only way that that error is appearing.

Can you run the steps again, but from a test location and place only one show in there as test 1. Then, add some more shows at that test location as test 2. Then repeat 2 until you isolate the show that is causing the issue. Then add the .nfo of the show that you isolated.

Good luck.

**Comment by JackDandy** [comment]
Hello, 

I have run **two** tests with your steps and cannot reproduce this issue.

This leads to a corruption in a `.nfo` file that is causing this. You don't mention if in the logs there is a report of such a thing, but it is the only way that this error is triggering.

Can you run the reproduce steps again, but first move most of the shows listed in the import view to a temp location as test 1.
Then, as test 2, restore some shows from your temp location and import those.
Then repeat test 2 until you isolate the show that is causing the issue.
Finally, copy/paste the `.nfo` file in the isolated show folder to a gist and post the link to it below.

Good luck.

**Comment by JackDandy** [comment]
Hello, 

I have run **two** tests with your steps and cannot reproduce this issue.

This leads to a corruption in a `.nfo` file that is causing this. You don't mention if in the logs there is a report of such a thing, but it is the only way that this error is triggering.

Can you run the reproduce steps again, but first move most of the shows listed in the import view to a temp location as test 1.
Then, as test 2, restore some shows from your temp location and import those.
Then repeat test 2 until you isolate the show that is causing the issue.
Finally, copy/paste the `.nfo` file in the isolated show folder to a gist and post the link to it below.

Good luck.

**Comment by JackDandy** [comment]
The corruption in your `.nfo` file has been found without needing your input. A fix will be merged shortly.

**Comment by JackDandy** [comment]
Fix [here](https://github.com/SickGear/SickGear/releases/tag/release_0.22.1)

Thanks for the report.

**Comment by tenpin784** [comment]
Thanks! Works now! 

Awesome quick reply and fix!
