### ISSUE TITLE
Loading of SickGear Web UI stuck on "Starting up... loading" with spinning wheel

### ISSUE THREAD

**Issue by nanouk76** [SickGear/SickGear#1327]
Installed from git, master branch as of today Friday November 27.

Followed **all** steps from the **manual install** procedure as documented in the wiki, on Ubuntu 20.04 system, 64bits.

Running "sudo -u username (replaced with my user of course) python sickgear/sickgear.py" results in the console window indicating "Starting up        Loading:" but nothing else. As per the title of the issue, the page in the browser (Firefox) displays the same message.
Python version: Python 2.7.18
Log says:
`2020-11-27 08:29:42 INFO     TORNADO :: Starting SickGear on http://0.0.0.0:8081/
2020-11-27 16:28:27 INFO     TORNADO :: Starting SickGear on http://0.0.0.0:8081/
`
I am at a loss.
Any help appreciated
TIA

**Comment by JackDandy** [comment]
The sections requested when this issue was created, enables your reported issue to be replicated and investigated, however, you removed it so there is no idea how to trigger your reported event in order to fix it for you. Until you can supply this information, then there is no choice but to mark this issue "invalid" as what you are reporting cannot be verified. Sorry.

Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

There's no need to open a new issue, additions to the end of this thread are just fine.

Thanks.

**Comment by nanouk76** [comment]
#### Branch: Master
#### Branch version commit hash: 1f32e05 @ 0.23.2


Re-install SickGear after an update in develop branch nuked my installation | Web UI loading but stuck on "Starting up       Loading..." 
------------ | -------------
No matter what I do (delete folder, reboot computer, re-install from git) running "python sickgear/sickgear.py" amounts to the same thing | Command line run in console to start SickGear prints "Starting      Loading:" but nothing else and nothing else happens

Additional notes:
- computer running Ubuntu Desktop 20.04
- python version 2.7.18
- perms on sickgear folder, inside my home, are correctly set as per the manual install instructions (vanilla install)

Since the log file contained only the two lines in original post, I decided to pipe the output of "python sickgear/sickgear.py" to a file and lo and behold the loading ran its course and I wa sable to get to the web UI. This is reproducible.

**Comment by JackDandy** [comment]
Can you come to IRC, i would like you to do some tests, and doing it via this thread is too cumbersome.

**Comment by nanouk76** [comment]
Thanks for replying.
Sorry I can't do it right now but will try to catch you on IRC tomorrow as soon as I can. Have to figure out how to do it... Any pointers?

**Comment by JackDandy** [comment]
Okay, well, I'll set up a virtual machine with `ubuntu-20.04.1-desktop-amd64.iso` and try the steps that you wrote to see if I can replicate here.

**Comment by nanouk76** [comment]
Thanks for your time. Great software by teh way :-))

**Comment by JackDandy** [comment]
Okay, I was able to very with a couple of tweaks SickGear manual install guide on the wiki.

Given that `ubuntu-20.04.1-desktop-amd64.iso` ships with `python3` there is no need to use python(2). Therefore, the wiki docs are updated to show this, and there are no issues running SG under this OS.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by nanouk76** [comment]
OK so I also ran a Ubuntu VM and it works as expected following the install steps, which I knew it would, of course.
Now how can I troubleshoot my problem since the logfile only contains the 2 lines I posted in my OP?
The big difference I noticed between the VM and my computer is that in the VM, running "python sickgear/sickgear.py" prints a series of lines and opens the default browser that prints the initial ckecks and eventually displays the SickGear home page, whereas on my computer it runs a kind of console browser that prints the same message as the web page in Firefox with only "Starting Loading:"

**Comment by JackDandy** [comment]
> whereas on my computer it runs a kind of console browser
  
that is clearly non standard, we both proved that by running vanilla Ubuntu installation, I don't know what it is, but it sure sounds to be the cause.

> if I run `python sickgear/sickgear.py &> ~/out`, it now runs as expected  

the SG output that normally goes to the terminal is now redirected to a file called `out` in your root folder,  therefore, whatever is conflicting with your terminal output is no longer screwing SG and so it is able to output and run without issue instead of being blocked.

As you have found, a vanilla Ubuntu runs everything fine.  A default SG installation will open a browser on startup. Your computer is not doing these things, therefore, you need to fix whatever is causing this issue, it is defo not an SG issue.

**Comment by herkalurk** [comment]
@nanouk76 if you're having this many problems it may be in your best interest to look into using [docker ](https://github.com/SickGear/SickGear.Docker) to run the application instead of directly on your ubuntu installation.

**Comment by JackDandy** [comment]
> on my computer it runs a kind of console browser that prints the same message as the web page in Firefox with only "Starting Loading:"

I highly suspect that the `kind of console browser` that is attaching itself to the output of SG is the root cause of this issue. It is intercepting SG output, and is probably not capable of running Javascript, therefore, it is blocking SG from running.  A docker isolates SG from external stuff that can interfere with SG, so as suggested above, if you cannot find how to disable the root cause, then use Docker to circumvent. Personally, I would prevent the text based browser from automatically interfering from my native running applications.

**Comment by JackDandy** [comment]
> on my computer it runs a kind of console browser that prints the same message as the web page in Firefox with only "Starting Loading:"

I highly suspect that the `kind of console browser` that is attaching itself to the output of SG is the root cause of this issue, what is it called? Anyway, it is intercepting SG output, and blocking SG on startup. SG was never designed to run with text based browsers.  Firefox, Chrome, IE, Edge, and modern full graphic browsers are supported. 

Now, Docker isolates external stuff from interfering with it, so as suggested above, if you cannot find how to disable the root cause, then try SickGear Docker to circumvent it. Personally though, I would prevent the text based browser from automatically interfering with my native running applications.

In light of this case, a warning has been added to the main installation wiki page about text based browsers.

**Comment by nanouk76** [comment]
The weirdest thing is this apparent text based browser issue that I have no clue about, I have absolutely no inkling for those types of browser so find it preposterous that there would be one installed... The more I think about it i seem to remember that since this issue cropped up I have seen the complete home page rendered in text at some point. Now the plot thickens and I don't know where to start. Just so that I have a clue, how does SickGear run the default browser? Does it get its info from the OS?

**Comment by JackDandy** [comment]
The built-in Python webbrowser controller module is called from [this SickGear logic](https://github.com/SickGear/SickGear/blob/master/sickbeard/__init__.py#L2296) - in turn, the controller handles how it will invoke a browser based on OS and other things according to the Python [webbrowser documentation](https://docs.python.org/3/library/webbrowser.html).

**Comment by nanouk76** [comment]
Woot! I think I found the culprit.
I first listed the available browsers on my system
`apropos browser
sensible-editor (1)  - outils pratiques d'édition, de mise en page et de navigation sur le web
firefox (1)          - a free and open source web browser from Mozilla
git-web--browse (1)  - Git helper script to launch a web browser
infobrowser (1)      - read Info documents
libsmbclient (7)     - An extension library for browsers and that can be used as a generic browsing API.
sensible-browser (1) - sensible editing, paging, and web browsing
viewres (1)          - graphical class browser for Xt
w3m (1)              - a text based web browser and pager
www-browser (1)      - a text based web browser and pager`
So I decided to uninstall w3m (which, for the life of me, I don't know how it got installed) and re-ran SickGear startup script with the expected behaviour, hoorah!

**Comment by nanouk76** [comment]
Sorry, I don't know how to quote console output, so it's rather jumbled in my previous post

**Comment by nanouk76** [comment]
> The built-in Python webbrowser controller module is called from [this SickGear logic](https://github.com/SickGear/SickGear/blob/master/sickbeard/__init__.py#L2296) - in turn, the controller handles how it will invoke a browser based on OS and other things according to the Python [webbrowser documentation](https://docs.python.org/3/library/webbrowser.html).

That's why it got stuck, not finding one of its target browsers, phew!

**Comment by JackDandy** [comment]
No, I would **not** conclude that Python could not find the browser. If that was indeed the case, then Python would simply return back to the logic with an `exception` raised, which is handled with a second attempt, and then a message output from SG "Unable to launch a browser". 

Therefore, no. The text based browser `w3m` locks the thread and does not return back to SG so that it can continue with its startup process.

**Comment by nanouk76** [comment]
> 
> I wonder why Firefox is not the first priority browser to launch on your computer, this is not a default, given this doesn't happen on a new Ubuntu installation.
So do I... Maybe it was installed when I tinkered a little with Netdata. I don't really know. I don't use that computer much, especially for browsing anyway, it's in the basement running a couple servers AND SickGear and I mainly ssh into it.
Thanks for your time anyhow, was much appreciated :+1:
