### ISSUE TITLE
Text Color in Dark Mode

### ISSUE THREAD

**Issue by Tonkapug** [SickGear/SickGear#1331]
This is not an issue with the operation of SickGear (it works just great) but more of a request. Is it possible to change the colour of the text under the 'Downloads' section of the 'Show List' menu item? The colour with dark mode enabled is currently white with a light green background and it's very difficult to see. I think black would possibly work much better.

**Comment by JackDandy** [comment]
hi,, sorry i do not follow, can you send a screenie because that doesn't wound right.

**Comment by JackDandy** [comment]
Sorry i do not follow, can you send a screenie because that doesn't sound right.

Also, **all** the things asked of you when you created this request, you removed and ignored, so now i have to waste time asking you to please enter all the things requested in order for me to try and see what you see, which i don't currently see on my browser.
