### ISSUE TITLE
Automatic handling for failed downloads not working with SABnzbd

### ISSUE THREAD

**Issue by boredazfcuk** [SickGear/SickGear#1356]
#### Branch version commit hash: COMMIT: 5a1a122 @ 0.25.0

Expectation | Result
------------ | -------------
When a download in SABnzbd fails, SickGear recognises this and then tries another release | This does not happen. I have to manually change selected episodes to failed.

**Steps to reproduce:**
*1)* Enable failed download handling in SickGear
*2)* Disable _Abort jobs that cannot be completed_ and _Post-Process Only Verified Jobs_ in SABnzbd
*3)* Enable _empty_postproc_ in SABnzbd
*4)* Wait for a download to fail
...

A sanitised version of the relevant logs can be found [HERE](https://pastebin.com/871vcQkU).

According to the logs, multiple download locations on the initial search, but then after the download fails, these are not attempted.

P.S. Thanks for all the great work you put into this project. Really enjoying the new version. The actor thumbnails are great.

**Comment by JackDandy** [comment]
Please can you read [this](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B80%5D-Extras#sabnzbd) and thoroughly check your set up, because there is nothing we have done to affect that code. Looking at the logs, that episode is s00. which could have caused confusion.

**Comment by boredazfcuk** [comment]
It used to work but stopped working a while ago, around the release time of when SAB started defaulting to the "Glitter" skin (about SAB 3.2.0 IIRC). It didn't bother me much at the time, as failed downloads were few and far between. I'm seeing them very frequently now though, which I why I thought I'd report the issue.

My setup was using the nzbToSickBeard.py script that comes with nzbToMedia, I'll swap to sabToSickGear.py and see if that gives better results.

S00E00 was just part of sanitising the logs. The actual show would easily be identified from the current Season/Episode number.

**Comment by JackDandy** [comment]
Perhaps SAB changed something, we will need your exact test data in the hope that your failure can be replicated in the investigation, perhaps @Safihre has an idea?

**Comment by JackDandy** [comment]
Yeah, the first action here is to actually try the SG script as the issue you presented is a third party script that we do not support .

Currently, there is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
@boredazfcuk how did your test go ?

**Comment by boredazfcuk** [comment]
Hi,

I've not tried it as yet, I run Sab in a separate container to SG so I had to re-write my Sab Dockerfile to include pip;requests, and then to clone your repo to obtain the AutoProcessTV.py and sabToSickGear.py files.

I've just kicked off a test now, hopefully I'll see some failures and will report back.

**Comment by JackDandy** [comment]
its a shame you could not point sab scrtips dir setting directly to the sg AutoProcessTV folder (thus saving hassle with requests:pip and such) like what is done in normal setups, but it sounds like you know what you're doing, so fingers crossed.

**Comment by boredazfcuk** [comment]
Well, it's been going for an hour now, but nothing's failed so far. There's 70 items in Sab's queue... hopefully a couple of them will have failed by the morning so I'll update then.

**Comment by boredazfcuk** [comment]
Just my luck that everything came down without an issue... I'll try something else tonight.

The shows I've been having problems with are due to come down in the next few days so hopefully I should see a couple of real world failures soon.

**Comment by boredazfcuk** [comment]
So something "failed" this morning.

SAB gave me a warning that the episode was only 98% completed, stating it may fail because it wasn't 100.2% complete. It downloaded it and then ran sabToSickGear.py. The script log stated `Failed download detected`, `Deleted folder`, `Successful failed download processing` and finally `Successfully processed.` I've checked the episode and it is in my library. All good.

So it seems like SAB pre-checks the download, finds it's likely to fail, so marks it as a "failed"download at this point. It then downloads the episode, which completes OK, but SAB still invokes sabToSickGear.py with a failed status. sabToSickGear.py doesn't find a problem and then adds it to my library without issue.

I believe nzbMedia's nzbToMedia.py script handled this differently. If the script was invoked with a failed status, it just deletes the files, then fails to inform SickGear of the failed status, so no alternative .nzb is attempted.

So I'm not entirely sure what the cause of this is. The only thing I think it could be is propagation... SAB detects the episode as 98% complete, but by the time it gets to the end of the download, it is 100% complete and everything is downloaded. It seems that SAB is setting the 'failed' status prior to download, based on the result of the article check, rather than post download. I've changed my category priority from `Force` to `High` which should introduce a 15 minute propagation delay.

I've also managed to find a show that has been removed from usenet. sabToSickGear is operating as expected. SAB fails the download, sabToSickGear correctly informs SG that the download has failed, a new download is then attempted.

So, all in all, it seems that switching over to the sabToSickGear.py script has fixed both issues.

Thanks for your help.

**Comment by JackDandy** [comment]
SABnzbd devs (@Safihre @sanderjo @jcfp @puzzledsab) may appreciate these findings so I dutifully tag them in.

So, a main takeaway from your findings raises a possibility that SAB can invoke scripts with failed status at 98% complete before the transfer actually finishes with 100% due to article propagation during the transfer window period, this of course has a range of consequence that can be best handled at the moment by **forcing** the enable propagation delay in SAB.

**Comment by JackDandy** [comment]
SABnzbd devs (@Safihre @sanderjo @jcfp @puzzledsab) may appreciate these findings so I dutifully tag them in.

So, a main takeaway from your findings raises a possibility that SABnzbd can invoke scripts with failed status at 98% complete before the transfer actually finishes with 100% due to article propagation in real-time during the transfer window period, this of course has a range of consequence that can be best handled at the moment by **forcing** the enable propagation delay in SABnzbd.

**Comment by Safihre** [comment]
I am 98% (pun intended 😉) sure that this is not normal SABnzbd settings/working, there are some special scripts at work here.
If the pre-check says it's failed, it will not just re-add it to the queue, it will fail it and it will stay in the History. 
It won't just add it with failed flags.

**Comment by JackDandy** [comment]
Timely pun @safihre ;)

So when a failure event is raised near the end of a transfer, an article processing thread cannot continue and complete the download to 100% ?

**Comment by boredazfcuk** [comment]
Hmmm... Just to confuse matters even more...

>SAB gave me a warning that the episode was only 98% completed, stating it may fail because it wasn't 100.2% complete. It downloaded it and then ran sabToSickGear.py. The script log stated `Failed download detected`, `Deleted folder`, `Successful failed download processing` and finally `Successfully processed`. I've checked the episode and it is in my library. All good.

I've just double-checked the episode in my library and noticed that it was 150MB in size, which is a good deal smaller than I would expect.  I've then re-added the original .nzb and this time around the article check did not mark it as "Incomplete". The download also completed successfully, so this again points to a usenet propagation issue.

I've then checked the new file in my library and it is 725MB rather than 150MB.

It seems that the sabToSickGear.py script processed the file as failed, but instead of deleting it and sourcing an alternate .nzb, it moved a partially extracted .mkv to the library.

**Comment by JackDandy** [comment]
hmm, my understanding is that there should not even have been a file available for processing if said file was not 100% complete.

**Comment by Safihre** [comment]
If you disable  `Post-Process Only Verified Jobs`, indeed this can happen.

**Comment by boredazfcuk** [comment]
I also have `Abort jobs that cannot be completed` disabled.

Presumably this is what allowed the incomplete job to progress, as it was in the 80-99% complete range.

**Comment by JackDandy** [comment]
Also, in the SG UI since like forever, has been the guidance to disable that option. I believe with it enabled, SAB **_used_** to not send a failed notification, but maybe this has now changed?

We should also probably add another guidance as "must enable propagation".

**Comment by boredazfcuk** [comment]
If both these options are disabled, then jobs with the number of articles in the 80-99% range will be allowed to proceed.

This could be true for more reasons than just propagation, if the uploader just decides to quite mid-transfer, for example...

I guess in the majority of cases, incomplete downloads would be due to either propagation, or if the articles have been removed from the server.

The specific setting that bypasses the propagation delay was setting the tv categoy in SAB to priority `Force`. I will set this to `High` from now on, and adjust my other categories accordingly.

**Comment by boredazfcuk** [comment]
> I believe with them enabled, SAB **_used_** to not send a failed notification, but maybe this has now changed since sab3+?

This was my memory as well. That the post-process script were not run if the job was aborted. The job had to fail for the script to run.

I've noticed that nzbToMedia's SickBeard script tells users that they should enable `Abort jobs that cannot be completed` so maybe this behaviour has changed.

**Comment by JackDandy** [comment]
@boredazfcuk nice, If you can test and let me know without the propagation mitigation which prevent you from seeing if those setting do indeed block the failed message being reported.

I can change the guidance to reflect that SAB3.0+ needs to do the opposite to what SAB2 did in terms of those two options. But like you said, there are things like what happens when a user made abort happens.

**Comment by boredazfcuk** [comment]
Will do. I've got episodes due tonight/tomorrow/Tuesday/Wednesday so I'll see if the issue re-occurs.

It can be a bit tricky to catch though as the propagation window is short. Depending on when the episodes are uploaded and the time which SG searches for the episode, the files may have propagated before SG even finds them.

**Comment by boredazfcuk** [comment]
Hi,

I've not seen this issue since changing the priority of Sab TV downloads to priority "High" and not run into this issue since. Six new episodes in all, have come down.

I've also have `Abort jobs that cannot be completed` enabled now and this works very well. I added a show which has long been deleted from usenet. It failed three or four .nzbs per episode before adding torrents. Having this enabled means that nothing has to be downloaded before the job is failed, saving time and bandwidth.

**Comment by JackDandy** [comment]
Unfortunately, nothing in your feedback reports effects of the settings in isolation that are the ones under scrutiny because you did not disable High, and that option simply glosses over any outcome from other settings due to it enabling a delay before beginning to download. Another user may not want their SABnzbd installation to wait before download, and therefore, we do not know the real effect of these settings.

**Comment by boredazfcuk** [comment]
Just reporting that SG is reliably downloading successfully now that the TV category (which is solely used for SigGear downloads) is set to High and has the "propagation delay" of 15mins.

I will set back to High for the coming week to make sure that the `Abort jobs that cannot be completed` option handles the error correctly if articles aren't fully propagated.

**Comment by boredazfcuk** [comment]
So I have another "failure" this morning.

SABnzbd history reports `Aborted, cannot be completed - https://sabnzbd.org/not-complete`. It has a status of `Failed` with 109 malformed articles.

However, the script output shows (name changed for privacy):
```
Loading config from /nzbToMedia/autoProcessTV.cfg

Opening URL: http://sickgear:8081/sickgear/home/process-media/files
Checking folder... /storage/downloads/incoming/sabnzbd/Some.TV.Show.S10E10.720p.HDTV.x264-GROUP
Processing folder... /storage/downloads/incoming/sabnzbd
Processing sub dir: Some.TV.Show.S10E10.720p.HDTV.x264-GROUP
Failed download detected: (Some.TV.Show.S10E10.720p.HDTV.x264-GROUP.nzb, /storage/downloads/incoming/sabnzbd/Some.TV.Show.S10E10.720p.HDTV.x264-GROUP)
Deleted folder /storage/downloads/incoming/sabnzbd/Some.TV.Show.S10E10.720p.HDTV.x264-GROUP
Successful failed download processing: (Some.TV.Show.S10E10.720p.HDTV.x264-GROUP.nzb, /storage/downloads/incoming/sabnzbd/Some.TV.Show.S10E10.720p.HDTV.x264-GROUP)
-----------------------
Successfully processed.
```
This episode is showing in my library, but I can't check the integrity of the file for another 10-12hrs or so. Size wise, it's a little on the small size, but not so much that it's obviously corrupt. I'll check later tonight and let you know.

**Comment by JackDandy** [comment]
> Sab just doesn't have a good way to always run scripts. 

@Safihre I really appreciate your clarification, and thank you for looking into this.

> Querying the history API to get the status instead of using a script

The **polling** model *cough rabbit hole* is one that SG consciously avoided as the **push** model that SAB and SickBeard originally designed is/was always far more efficient for the invested effort of setting up the script in the SAB category interface, in my opinion, genius design.

Then there is the consideration of an entire series that partially completes, this outcome is clearly why a folder is processed regardless of the status input variable passed from SAB - given 23 of 24 episodes could be perfectly fine.

This leads to a conclusion that there is not _much_ that SG can change. 

However, a solution that uses an external command line binary to evaluate the integrity of clearly identified media filenames and delete bad ones, is probably the most interesting and proven.  A concern is binary compatibility across architectures from ARM to AMD, but something is better than what we have now, which is nothing.

@boredazfcuk if you would like to add this feature to `sabtoSickGear.py` - then other folk could add the binary media validator that is fitting for their system into a new `autoProcessTV/mediacheck/` folder as part of the optional post installation tasks, I could make core check for the existence of that binary and add a note to the config media process page (like we do for unrar) - interested ?

p.s. folk should enable propagation delay in order to reduce failures in the first instance, that's a clear take away from this thread.

**Comment by JackDandy** [comment]
> Sab just doesn't have a good way to always run scripts. 

@Safihre I really appreciate your clarification, and thank you for looking into this.

> Querying the history API to get the status instead of using a script

The **polling** model *cough rabbit hole* is one that SG consciously avoided as the **push** model that SAB and SickBeard originally designed is/was always far more efficient for the invested effort of setting up the script in the SAB category interface, entirely a genius design, imho.

Then there is the consideration of an entire series that partially completes, this outcome is clearly why a folder is processed regardless of the status input variable passed from SAB - given 23 of 24 episodes could be perfectly fine.

This leads to a conclusion that there is not _much_ that SG can change. 

However, a solution that uses an external command line binary to evaluate the integrity of clearly identified media filenames and delete bad ones, is probably the most interesting and proven.  A concern is binary compatibility across architectures from ARM to AMD, but something is better than what we have now, which is nothing.

@boredazfcuk

> and it didn't leave incomplete data.

I wasn't clear, I meant data that is a % incomplete of **one** particular file, not a season pack. Anyway, this conflict of mutually exclusive outcomes between a valid existence of a % of a files less than 100%, and a invalid % of one file, leads to the validator solution being the best route to handle these opposing scenarios.

So, if you would like to add this feature to `sabtoSickGear.py` - then other folk could add the binary media validator that is fitting for their system into a new `autoProcessTV/mediacheck/` folder as part of the optional post installation tasks, I could make core check for the existence of that binary and add a note to the config media process page (like we do for unrar) - interested ?

p.s. folk should enable propagation delay in order to reduce failures in the first instance, that's a clear take away from this thread.

**Comment by boredazfcuk** [comment]
Sorry I've been MIA, home life getting in the way.

To be honest, I've no idea how to go about this in Python. If I was doing in via Linux command line, I'd just call ffmpeg, re-encode the file to the bitbucket, and check it completes without error... Possibly check the container using mkvmerge/mkvinfo too.

But looking at the nzbToMedia script which has error checking built in (def is_video_good: https://github.com/clinton-hall/nzbToMedia/blob/master/core/transcoder.py), I wouldn't know where to begin... I did start a udemy Python3 course during lockdown, but I only got to "while loops" before my work decided that covid was over, and everyone needed to be back in the office.
