### ISSUE TITLE
Memory usage woes

### ISSUE THREAD

**Issue by cracklejoy** [SickGear/SickGear#1382]
I've been having issues lately with sickgear using up all my systems available memory.  I've been running sickgear for many years and it's only recently I see it using up all my memory.  

I need to kill the process manually and restart sickgear.  I'm not sure how to troubleshoot this.  This is now the second time it has happened and each time I do an update to the latest revision of sickgear and hope for the best.  

Running Ubuntu 20.04.4 LTS.

**Comment by JackDandy** [comment]
The steps section requested when this issue was created, enables your reported issue to be replicated and investigated, however, you removed it so there is no idea how to trigger your reported event in order to fix it for you. Until you can supply this information, then there is no choice but to mark this issue "invalid" as what you are reporting cannot be verified. Sorry.

Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

There's no need to open a new issue, additions to the end of this thread are just fine.

Thanks.

**Comment by cracklejoy** [comment]
Thanks for the quick close I'll be sure to move on to another project.  Good luck.
