### ISSUE TITLE
Install SickGear on OSMC running on RPi

### ISSUE THREAD

**Issue by Martin-D87** [SickGear/SickGear#1386]
Good day.

I trust that all is well.

Firstly apologies for making a new post on something that might have a thread already. Struggling to find a related thread.

For the last couple of months I have been having issue trying to run sickrage on my RPi. This morning I stumbled across SickGear, I follow the minimalistic looking guides on the net but to no success. I must admit that my skills with this kind of thing is abysmal.

When using this install guide I am encountering errors on the last step "sudo /snap/bin/sickgear"
_[[Install SickGear [11] RaspberryPi · SickGear/SickGear Wiki · GitHub](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B11%5D-RaspberryPi)
](https://github.com/SickGear/SickGear/wiki/Install-SickGear-%5B11%5D-RaspberryPi)_

The Snap installation goes well, however when I run the sudo /snap/bin/sickgear command I encounter errors as per the below:

_osmc@osmc:~$ sudo snap install sickgear

sickgear 0.25.25 from SickGear installed

osmc@osmc:~$ which sickgear

/snap/bin/sickgear

osmc@osmc:~$ sudo /snap/bin/sickgear

ERROR: ld.so: object ‘/usr/lib/libarmmem.so’ from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

ERROR: ld.so: object ‘/usr/lib/libarmmem.so’ from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

ERROR: ld.so: object ‘/usr/lib/libarmmem.so’ from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

ERROR: ld.so: object ‘/usr/lib/libarmmem.so’ from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

Starting up SickGear from /var/snap/sickgear/common/data/config.ini

07:55:58 INFO TORNADO :: Starting SickGear on http://0.0.0.0:8081/

07:55:58 ERROR TORNADO :: Could not start webserver on 8081. Exception: <class ‘socket.error’>, Error: [Errno 1] Operation not permitted

07:56:28 ERROR MAIN :: Unable to start web server, is something else running on port 8081?

07:56:28 ERROR MAIN :: Launching browser and exiting_

Will it be possible to kindly assist me?

Kind Regards;
M

**Comment by JackDandy** [comment]
Hi,

I can only guess that OSMC has changed since that doc was created and therefore it no longer works, we cannot advise on how to fix the snap but there are users running from source on RPi, so if you care to create an install doc to share that install method, then we can put that on the wiki.

**Comment by JackDandy** [comment]
Hi,

I can only guess that OSMC has changed since that doc was created and therefore it no longer works, 

[edit] yup, new line added... `sudo snap install core` ... can you confirm if the steps presented [here](https://snapcraft.io/install/sickgear/raspbian) work for you.

Additionally, there are users running from source on RPi, so if you care to create an install doc to share that install method, then we can put that on the wiki.

[edit 2] I have just been told the following...

`you can read about that error message in muliple issues for different apps, all realated to a weird rpi configuration:` 

- https://github.com/nextcloud-snap/nextcloud-snap/issues/1438 
- https://github.com/go-gitea/gitea/issues/17462

There is a solution in there to stop the error
