### ISSUE TITLE
Sickgear not working with Python 3.11.2 on Ubuntu latest

### ISSUE THREAD

**Issue by ebmanley** [SickGear/SickGear#1428]
Sickgear not working with Python 3.11.2 on Ubuntu latest

The application wont start due to a check at the beginning startup

**Comment by JackDandy** [comment]
upgrade, you are on deprecated version.

**Comment by JackDandy** [comment]
Correct.

You are on an old deprecated version, you need to upgrade SG or reinstall if you would like to continue.

This is already covered in the [wiki](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#how-to-update-legacy-sickgear-with-a-new-unsupported-version-of-python)

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.
