### ISSUE TITLE
Illegal instruction on updating TheTVDB

### ISSUE THREAD

**Issue by elerion64** [SickGear/SickGear#1429]
#### Branch version commit hash: f92f9f8

Expectation | Result
0 | Illegal instruction

14:04:52 INFO STARTUP-FORCE-SHOW-UPDATE :: Fetching show ids with xem scene mappings for origin TheTVDB
14:04:52 INFO STARTUP-FORCE-SHOW-UPDATE :: Finished fetching show ids with 1400 xem scene mappings for origin TheTVDB
14:04:52 INFO STARTUP-FORCE-SHOW-UPDATE :: Checking for scene exception updates for TVmaze
14:04:52 INFO STARTUP-FORCE-SHOW-UPDATE :: Checking for scene exception updates for TMDb
14:04:52 INFO STARTUP-FORCE-SHOW-UPDATE :: Checking for XEM scene exception updates for TheTVDB
Illegal instruction
root@nas:/opt/SickGear#

**Steps to reproduce:**
1) Install build release/3.28.0
2) Start with -f to immediately reproduce the error.
Server exits wihth "illegal instruction" immidiately after "Checking for XEM scene exception updates for TheTVDB" message.

**Comment by JackDandy** [comment]
What version of Python is this?
Is the Python a venv?
if you dont use "-f" and run the showupdate from Manage/Show Tasks, is it the same result today? (the issue may have been a server connection issue yesterday)

**Comment by JackDandy** [comment]
What version of Python is this?
Is the Python a venv?
if you don't use "-f" and run the showupdate from Manage/Show Tasks, is it the same result today? (the issue may have been a server connection issue yesterday)

There are no important **debug logs** included with this report.

Essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

**Comment by JackDandy** [comment]
This is not a Python code issue or an issue in SG.

"Illegal instruction" means that some binary code is executed that is compiled for a different platform and not this one. So it's a Python or c-extension that is not compiled for the system it is being run on.

The guess is that it is the `orjson` lib.  Therefore, disable "package updates" in SG settings to prevent re-installation of uninstalled packages, and then uninstall it with `pip`.

There is not an actual issue here, therefore, as per our normal handling, this thread will now be marked invalid. Feel free to ask anything else below, even though it is closed that's no problem.

Good luck.

**Comment by JackDandy** [comment]
And if you feedback that removing x fixed the issue, then we could add a something to exclude that particular lib from future updates while keeping others up to date specially for the few that share your issue.

**Comment by JackDandy** [comment]
This is not a Python code issue or an issue in SG.

The answer to this is moved to [wiki](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#older-CPU)

Thanks for the report.  
  
Good luck.
