### ISSUE TITLE
MoreThan.TV and Shazbat.TV

### ISSUE THREAD

**Issue by jtwill** [SickGear/SickGear#369]
Any chance that MoreThan.TV and Shazbat.TV can be added as providers?

SickRage already has them, so if the SR code can be imported into SG with minimal modifications, it should go quickly...

**Comment by adam111316** [comment]
MoreThan.TV looks to be a non-english site, so it's not something we would support.

Does Shazbat.TV have an api? The current implementation in SR does not look like its complete at all.

**Comment by jtwill** [comment]
MoreThan.TV uses English language on the web page and tracks TV shows (and more) that use the English language. I'm not sure why you thought it was not English.

How do I check whether Shazbat.TV "has an API"?

**Comment by jtwill** [comment]
Can you at least provide an explanation for the "won't fix"?

**Comment by adam111316** [comment]
A quick google search "morethan.tv is a ROMANIAN Private Torrent Tracker for TV / MOVIES"

You can check out the Shazbat.TV FAQ or go ask one of their developers.

Won't fix means that we are not implementing anything unless other evidence is provided that we should

**Comment by jtwill** [comment]
Are you calling me a liar about MoreThan.TV? The people who run it are Romanian, sure. But as I already wrote above, the web page for the site is in English, and almost all of the shows it tracks are English. It is NOT a Romanian language tracker. Surely you realize that FreshOn.TV is also run by Romanians, and SickGear supports that tracker. 

I understand what "Won't fix" means. I was asking why this issue was labeled "won't fix". I responded to your concerns about MoreThan.TV, so that at least cannot be a reason for "won't fix".

And I asked how to check whether Shazbat.TV "has an API". I do not know exactly what you mean, which is why I asked. Why was this issue suddenly closed and marked "won't fix" without discussing that?

**Comment by adam111316** [comment]
My response was with regards to "I'm not sure why you thought it was not English." that was my reasoning as to why. I do not have any access to the site, hence why it was my assumption.

Just because an issue is closed doesn't mean it disappears. We can reopen and relabel issues as we see fit. We've established our own methods for dealing with bugs and issues and we stick by it, its not meant to cause any offense.

Now you say that MoreThan.TV is an english site, does that have an api?

If either of those sites do have an api, we'd happily like to work with those sites to create a provider in SickGear

**Comment by jtwill** [comment]
So, you are saying that when this issue is marked "won't fix" it actually does not mean that the SG developers won't fix it? What is the point of marking it "won't fix" and closing the issue? It makes no sense. Why not leave it as it was, open and NOT marked "won't fix"?

I still don't know what you mean by having an API. That term is so vague that it is not helpful.

But as I already said, SickRage supports MoreThan.TV. If SR can do it, then surely SickGear can do it. Here is the SR code for MoreThan.TV:

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/providers/morethantv.py

**Comment by adam111316** [comment]
By API we mean some kinds of post/get with a json or similar response type system. We do not like using screen scraping techniques (using lxml or bs4) as a small change in the source html can break the provider completely. 

Perhaps you should use SickRage as you seem familiar with them already.

**Comment by jtwill** [comment]
Perhaps I should use SickRage, but not because I am more familiar with SR than SG. 

I am looking to move from SickBeard, and I am considering SickGear and SickRage. I first looked at which providers they support. Ideally, I would like to see support for ToTV, MTV, and Shazbat. Unfortunately, SG supports ToTV but not MTV or Shazbat. SR supports MTV and Shazbat, but not ToTV.

So I tried posting an issue to SG and SR support, to add the missing providers. The response of the SR developers seemed reasonable -- they marked my issue as "feature request" and "low priority". Obviously the "low priority" is not ideal, but at least their response makes sense. The SG developers marked my issue as "won't fix" and closed it without an explanation.

So I am certainly leaning towards SickRage based on the reasonable way the developers handled my issue, and the handling of this issue by the SickGear developers does not inspire confidence.

**Comment by adam111316** [comment]
If you are only looking at providers as a measure of which program to choose. Then by all means go for that but don't complain when things go wrong.

Since you didn't respond to the original question as to whether or not they have APIs (json or similar), I will be locking this request shortly as this is in no way productive to anyone.

Please feel free to submit a [PR] (https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Contribute-Code) for the providers if you do find api to work with.

**Comment by JackDandy** [comment]
Added... [Wiki: Can you please add a provider](https://github.com/SickGear/SickGear/wiki/Frequently-Answered-Questions#can-you-please-add-a-provider)

**Comment by JackDandy** [comment]
Morethan.tv added thanks to the kind help of a user.
