### ISSUE TITLE
Newnab providers stop searching for additional results if tvdbid parameter is used

### ISSUE THREAD

**Issue by adam111316** [SickGear/SickGear#591]
BRANCH: pull/588/feature/ChangeStarifyNN / COMMIT: 1811f7176ef14551e7337086f28e253946e0af57

Expectation | Actual Result
------------ | -------------
Provider should continue searching using alternative naming patterns if valid results are found OR all naming patterns should be searched before attempting to validate results | Provider attempts to search using tvdbid and stops further searching if a tvdbid search finds a single result. No further attempt to use alternative naming occurs.

Steps:
1. Add a newznab provider which does support tvdbids
2. Add a show (I have used an anime in this case)
3. Perform a manual search using the magnifying glass on an episode.
4. Check logs for result

Logs: https://gist.github.com/adam111316/ba9ec2d48c059406a77b

**Comment by JackDandy** [comment]
I had this exact thought and it was pointed out why I was wrong.

Background, given that a show can be released under different names. alternative names are used when a string search fails. On the other hand, an ID search makes alternative string naming redundant. This is because an ID will return the correct show regardless of any string naming.  If an ID is returns invalid results, then the associated provider is at fault and should be told independently. e.g. "Showname should have an ID of abcd but it instead has an ID of xyz, can you fix"

Conclusion, this is invalid. There should be no change to this process.
