### ISSUE TITLE
PostProcessing Fails

### ISSUE THREAD

**Issue by rbhamilton** [SickGear/SickGear#699]
More accurately, PostProcessing fails to start in some situations.

Seems this is a known problem with SickRage and it looks like SickGear uses a lot of the same code.  The fix is fairly simple.  I did it with Notepad++ and I don't even know a word of Python.  Worked like a charm.  

Here's the thread on the fix:

https://github.com/SiCKRAGETV/SickRage/compare/7a432bd2eab0f74f89cdf330b0e1af342cf25030...5770d33ef96e619af764b452ea35ad33e5755add

**Comment by JackDandy** [comment]
Hi @rbhamilton 

Have you actually **proven** this issue to occur with SickGear ? If not, then we cannot simply copy code from elsewhere to here.

**Comment by rbhamilton** [comment]
Yes.  I've had files download and sit in my finished folder for 3 days.  They never get processed.  Zero entries in postprocessing in the logs.  Nothing happens.

I do a manual postprocess and everything works fine.  All the stacked up shows suddenly fire over to Plex in a big lump.  The automatic processing never starts on it's own.  

I made the change above and now everything works perfectly.  

But as I said, I don't program in Python.  I have zero idea what the change does.  For all I know it sends my SIN number to the Russian Mafia.  I'll let you smart people look at it and see if it's worth adding.  But it worked for me and solved my issue.  Just passing it along.

**Comment by JackDandy** [comment]
Ok, no problem, then can you list the exact steps to reproduce the issue so that i can recreate here and then test the code change properly.

**Comment by rbhamilton** [comment]
Sure.  These are the steps I use to reproduce the problem. 100% of the time.

Step 1:  Add a TV show to Sickgear
Step 2:  Wait for it to download
Step 3:  Wait for Sickgear to start post-processing. 
Step 4:  Go to Step 3

**Comment by JackDandy** [comment]
so you are saying that PP is complete broken ? That doesn't sound right.

**Comment by rbhamilton** [comment]
100% broken 100% of the time.  For me.  Can't speak to anyone elses experience.

I'm running Windows and have no permissions issue.  I have auto-update turned on for SG and it says it doesn't need an update so I would guess it's current.

I do have PP enabled.  Set to run every 10 min.  But it doesn't ever start.  Ever.

At least it didn't.   I didn't make any changes to the settings.  I just edited the schedule.py file as indicated above.  Now everything works fine.

Sorry but I really have no other info on this topic.  Didn't work - fixed it - now it's working.

**Comment by JackDandy** [comment]
ok thanks for all the info - that helps a lot :)

**Comment by rbhamilton** [comment]
Lol... ya.  I also hate bug reports like this.  I support a legacy software package.  Normally it's a blue haired old lady saying "when I hit some button something came up on the screen and now nothing works!"  Mmm... ok I'll get right on that.

**Comment by JackDandy** [comment]
all i can do right now is laugh

**Comment by JackDandy** [comment]
Another question though...
can you go to help page and list the version here.

**Comment by JackDandy** [comment]
Ok, I think I have the issue, you made the code change and then restarted SG, it is actually the _restart_ that triggered the PP to function.

To test my theory...
1) Disable the "Scan and post process" option in PP, then click save.
2) Stop SG,
3) Undo the code change that you copied. 
4) Start SG
5) Make sure that there no PPs take place
6) Enable the "Scan and post process" option in PP, then click save.
7) As per your OP, make sure that there is still no PPs taking place (this is what you thought a bug)
8) Restart SG
9) PP should work now as normal

The issue is simply that you didn't restart between enabling this feature, and that the feature doesn't auto-start once save has been pressed or tell you to restart. The change that you posted is one of many examples of placebo code - that's right, it does absolutely nothing - go figure.
