### ISSUE TITLE
Request: Add option to omit symbols from renamer

### ISSUE THREAD

**Issue by Th3MadHatter** [SickGear/SickGear#706]
Hey guys, I've been having major issues with kodie scraping file names like "Girls' night" or anything with an ' symbol in it. It simply ignores the files until i change them manually which is really a pain in the ....

Is it possible to write something simple that lets the renamer remove symbols like these from them after scraping the name from databases? I'm pretty sure it should be possible and not too much work... it would help me immensely though because I'm missing out on a lot of episodes now because it just doesn't show up and I don't constantly check my storage.

**Comment by JackDandy** [comment]
Hello @Th3MadHatter 

The fault is in the script that Kodi is using. You need to approach that developer and ask them to fix their code to handle a simple ' char.

Good luck.

**Comment by Th3MadHatter** [comment]
https://discourse.osmc.tv/t/osmc-often-doesnt-find-files-with-symbols/17218/2 <-- Kodi will most likely do nothing since they know about the issue.

**Comment by JackDandy** [comment]
No, I'm saying that it doesn't sound like a core Kodi issue at all, it sounds most likely an issue with a third party add-on that is scraping for tv show meta data.  Personally, I don't use those, I use SGs post processing meta data features. Kodi (Isendgard) is able to play files fine, I have had zero issues playing files with ' in the file name.

**Comment by Th3MadHatter** [comment]
I don't use any extra addons for scraping. Once the file is finished it goes through nzbtomedia and is then picked up by SG.
Then it goes to OSMC through NFS, I have NOTHING installed except for the rapier skin and the trakt.tv addon to keep track of my media but none of those are used for anything, everything is set to use the default options.

**Comment by JackDandy** [comment]
Your OP reads ...
>  I've been having major issues with kodie scraping file names like "Girls' night" or anything with an ' symbol in it

If you can say the name of the show and the episode, i will snatch it and see if my Kodi plays it over the network from a NTFS drive, if it does then that proves that your issue needs to be fixed in the filesystem or something.

**Comment by Th3MadHatter** [comment]
Try anything from "Gamers' guide to pretty much everything" its a kids show I know it fails to even load the directory because of the "Gamers' " part.

**Comment by JackDandy** [comment]
Does the folder name "Gamer's..." look correct, or does it have funny chars at the point of the quote ' char ?

**Comment by Th3MadHatter** [comment]
No it looks incorrect since the name of the show is **Gamers'** guide not Gamer's Guide, it would most likely have worked if it was Gamer's. No other characters are used (its a US show so nothing weird).

**Comment by JackDandy** [comment]
Well that's not what I see here.... I see **Gamer's**
http://i.imgur.com/GJxirnZ.png

**Comment by Th3MadHatter** [comment]
The original name is Gamers' so just rename it so you can see it error out, it looks like the name changed on my end as well, must have been an initial typo which caused the season pack to be renamed to gamers' but either way thats the only example I can come up from the top of my head since I just cleaned out everything I "missed" and just marked everything as "seen" and just cut my losses for now. 
Its really with ANYTHING that's named with and ' behind or before its name or at a random place where it normally shouldn't be so it shouldn't be hard to reproduce either way.

**Comment by Th3MadHatter** [comment]
Ok i'm just relaying this as for what you said about kodi not taking ' into account in general. First of all everybody tells me to go here and make the script dev (I obviously can't say which or help will stop) to "make a simple fix to be able to omit 's " and here is an explanation why (even though its a bit rude, just read around it):
[quote] And what happens if the show name should have a : in it. That will work fine on linux, but not on windows. Ask the developer who is refusing to fix his script about that.... The Kodi developers are trying to use naming conventions that work for all OSes. Looks like the developer of the script you are using doesn't care about conventions. [/quote]

**Comment by JackDandy** [comment]
Yes we have a convention name sanitiser however ' is not considered illegal, chars like : and \ are.

I vaguely remember some issue with a release of **Marvel's Jessica Jones** where the episodes were re-released with the single quote ' removed, perhaps because someone saw an issue, I see that the directory name still contains a ' char though.

Also, there is **How It's Made**, **It's Always Sunny in Philadelphia**, **Da Vinci's Demons**, **DC's Legends of Tomorrow** and in every case, the folder name contains ' _**but**_ the file names do not have a '. Therefore, this leads me to ask  what is your Episode Name Pattern on the PP Episode Naming tab ?

In any case, we absolutely need a test case or else we have nothing to prove or disprove any code change actually has an effect - without this, a change cannot be made. So you **must** find a case.

**Comment by Th3MadHatter** [comment]
Indeed but the names as you state them are general It's, Vinci's etc. those often do seem to work as directory names (got all of them except for How its made) but the biggest issue lays with files names with a ' in weird places like after the word or in the middle of a word where they randomly made it up like "friggin'epic" thats not a normal name and Kodi will fail on it, if the ' is removed it works just fine.
One thing is for sure though it NEVER adds anything with a ' at the END or BEGINNING of a word.

If I find a proper example I'll let you know, sometimes it happens with things with , or ? or ! as well but it seems to be more rare.

As for my PP profile

Pattern: Custom
Episode naming: Season %0S/%SN - S%0SE%0E - %EN
Multi episode style: Repeat

Single episode sample:
Season 02\Show Name - S02E03 - Ep Name.ext

Multi episode sample:
Season 02\Show Name - S02E03E04E05 - Ep Name.ext 

Nothing else checked.

**Comment by JackDandy** [comment]
And there is the confusion, because Kodi successfully navigates folders with **'**, then it is reasonable to expect Kodi to handle the **'** char in file names as well - but apparently, it has pretty inconsistent handling - is there documentation for unacceptable characters. 

> sometimes it happens with things with , or ? or !

"sometimes" is not reliable, we need "always" proof scenarios.

I have just found a file on my system...
**The.Boondocks.S03E01.It's a Black President, Huey Freeman.SD.TV.avi**
that contains both a **'** and a **,** and that plays on my Kodi Isendgard with no issue.

Anyway, this issue can sleep until a robust test case becomes available.

**Comment by Th3MadHatter** [comment]
Nope you still don't get it. I got that boondocks ep as well btw.
The EPISODE NAME has to END with a ' like "My New Random Show - S03E11 - American Descendants'.mkv"  

That always fails to load in kodi, it simply does. (example if fictional, don't look for it, doesn't exist lol).

If episode was named "My New Random Show - S03E11 - Descendants' of America.mkv" it would ALSO FAIL 90% of the time.

If the file name is "My New Random Show - S03E11 - American Descendant's.mkv" it USUALLY (95% of the time) WORKS.

if the file name is "My New Random Show - S03E11 - Descendant's of America.mkv" it, as far as i know, ALWAYS WORKS (99~%).

If any of the above mentioned that TENDS to fail has an EXTRA symbol like ? in the middle of its name ( e.g. "My New Random Show - S03E11 - American? Descendants'!.mkv" or "My New Random Show - S03E11 - Descendants' of America!.mkv") IT INCREASES THE CHANCE OF FAILURE (50%).

I seriously hope you get it now because you where looking for things I wasn't even remotely talking about haha.

**Comment by JackDandy** [comment]
And Kodi say that they are not at fault with your findings ? OH MY GOD! LOL

**Comment by Th3MadHatter** [comment]
Kodi devs don't respond at all anymore, the biggest question I got from a kodi dev was "Are you sure it only happens with NFS or with SAMBA as well?" Which wasn't even my point I just listed my setup for completeness, not for actual use so I responded, "Of course it happens with samba as well I just named the file transfer for completeness" or something along those lines.

So end of it all I'm pretty sure Kodi support ended there meaning I still have an issue which will not be fixed, you say no, kodi says nothing so thats a royal "go fuck yourself when we have the issue ourselfs we'll start fixing it" from both parties xD. Not to be blunt but thats pretty much what it is, person A tells me to go to person B, person B tells me to go to person A, person A complains about person B, person B complains about person A, the end. PROBLEM STILL EXISTS nothing happened but people blaming each others projects.

**Comment by JackDandy** [comment]
What you say is simply not true,
1) I asked if they document bad chars so that i can add
2) I asked for a test case so that i can make sure that any work i do can be tested.
I have not complained about Kodi, indeed, i clearly said that i cannot find the issue here - I have tried to help but if this is how you will treat me, then I will shut down. Please do not make fiction up like that.

**Comment by Th3MadHatter** [comment]
I don't treat you like anything I just stated a fact. It could be you at fault, Kodi at fault, whoever at fault but that really doesn't matter. I didn't make up fiction (you never have to by the way, fiction is fiction, non fiction is non fiction) about anything, however, I never talk fiction, if I will it will be in a book labled that way, the above is exactly what happened, finger pointing and going back and forth. Either way. I gave you pretty much a billion and one test cases, all you have to do is make up an episode name with a ' behind it or infront of it and try and load it up you'll see that it instantly fails to load. But hey if you still don't get it and/or don't want to help anymore that's up to you of course, it would be petty since I didn't do anything but state the obvious but still totally up to you.

**Comment by JackDandy** [comment]
I did rename a file and added ' just before the /mp4 and it did work. This is why i ask you so many things, but you do not appreciate what i am trying to do for you. Anyway, I cannot test becuase you cannot show me how to test, therefore, I have added a private setting and you can use it yourself,I cannot do anything more than this, i hope it works for you because i cannot test it
https://github.com/SickGear/SickGear/pull/707

**Comment by Th3MadHatter** [comment]
Thank you! Idk why it does work for you but doesn't for me, i'm going to test this and if it stops happening i'll let you know :+1:
