### ISSUE TITLE
Feature Request - Ability to Disable Full Backlog

### ISSUE THREAD

**Issue by Sytanek** [SickGear/SickGear#805]
Would it be possible to get an option to just completely disable full backlog? And if this already exists and I am missing it, I apologize.

**Comment by JackDandy** [comment]
Hi, go to any enabled provider, and the option is there, set per provider.

**Comment by Sytanek** [comment]
The issue is that this disables force backlog search for specific shows as well. I have so many shows, I want to be able to manually do it, but never do a full on its own.

**Comment by JackDandy** [comment]
Okay so the other choice you have is to edit a show and "pause" it so that it won't be used in any backlog search, or use mass edit to pause several shows at once.

**Comment by JackDandy** [comment]
Oh so you don't want to disable backlog as you originally asked, okay, edit a show and "pause" it so that it won't be used in any backlog search, or use mass edit to pause several shows at once. When you're ready, "Change selected episodes" in paused shows to status "Wanted" in order to trigger a manual search.

If this still doesn't answer your question, then come to IRC.

**Comment by JackDandy** [comment]
This can now also be done at the provider config level...
disable `enable scheduled searching for backlogged episodes`
