### ISSUE TITLE
All torrent cache servers failed to return a downloadable result

### ISSUE THREAD

**Issue by exxie** [SickGear/SickGear#809]
Hi there,

I get this error message for a couple of days now: 
"2016-10-26 18:37:43 MANUAL-153021 :: All torrent cache servers failed to return a downloadable result"

Also, the automatich search does not work. Does this have to do with the newest sickgear version and will be fixed with the future update?

Thanks for looking into this.

ex.

**Comment by JackDandy** [comment]
essential help on [[How-to] Report Issues](https://github.com/SickGear/SickGear/wiki/%5BHow-to%5D-Report-Issues)

**Comment by kidburglar** [comment]
I think it's the same problem so I complete the issue.
Thanks in advance for your help.
Cheers.

Applies to: master (48cb3008cf85f06cdc2e5d4f9627f7dff96de74a)
Expectation | Result
------------ | -------------
Download episode S03E01 of Black Mirror with RARBG provider (automatically or manually) | No torrent files is downloaded
_[blank line]_

**Steps to reproduce:**
*1)* Go in the TV show (Black Mirror)
*2)* Launch the search for episode S03E01
*3)* Go in the logs & errors tab to see the message
_[blank line]_

<pre>
22:45:38 INFO::MANUAL-253463 :: Beginning manual search for: [Black Mirror - 3x01 - Nosedive]
22:45:38 INFO::MANUAL-253463 :: [Rarbg] :: Performing episode search for Black Mirror
22:45:38 INFO::MANUAL-253463 :: [Rarbg] :: 8 episode items in response from https://torrentapi.org/pubapi_v2.php?app_id=SickGear&mode=search&format=json_extended&category=18;41&limit=100&sort=last&ranked=0&token=6cqv9ih37l&search_imdb=tt2085059&search_string=S03E01&min_seeders=1
22:45:38 INFO::MANUAL-253463 :: Quality is 1080p WEB-DL for Black.Mirror.S03E01.1080p.WEBRip.x264-SKGTV[rartv]
22:45:38 INFO::MANUAL-253463 :: Quality is 1080p WEB-DL for Black.Mirror.S03E01.PROPER.1080p.WEBRip.X264-DEFLATE[rartv]
22:45:38 INFO::MANUAL-253463 :: Quality is 720p WEB-DL for Black.Mirror.S03E01.720p.WEBRip.x264-SKGTV[rartv]
22:45:38 INFO::MANUAL-253463 :: Quality is 720p WEB-DL for Black.Mirror.S03E01.PROPER.720p.WEBRip.X264-DEFLATE[rartv]
22:45:38 INFO::MANUAL-253463 :: Downloading Black.Mirror.S03E01.PROPER.1080p.WEBRip.X264-DEFLATE[rartv] from Rarbg
22:45:46 WARNING::MANUAL-253463 :: Connection error ('Connection aborted.', gaierror(-2, 'Name or service not known')) while loading URL https://torcache.net/torrent/E7D7DC53BB19306983C2B3750CE402889D93944A.torrent
22:45:46 WARNING::MANUAL-253463 :: Connection error ('Connection aborted.', gaierror(-2, 'Name or service not known')) while loading URL http://thetorrent.org/torrent/E7D7DC53BB19306983C2B3750CE402889D93944A.torrent
22:45:48 ERROR::MANUAL-253463 :: All torrent cache servers failed to return a downloadable result
</pre>
_[blank line]_

Additional notes:
It's a fresh install of SickGear with old database for the TV shows.
I configure only RARBG and subtitle providers.

**Comment by JackDandy** [comment]
Hello, 

First tip, as you are on 'master' branch, can you switch to develop and see if the issue still exists there...

<img src="http://i.imgur.com/5mGWD4b.png" />

**Comment by kidburglar** [comment]
I switch to develop branch and I have now another message.

<pre>
23:11:32 INFO::MANUAL-253463 :: Beginning manual search for: [Black Mirror - 3x01 - Nosedive]
23:11:32 INFO::MANUAL-253463 :: [Rarbg] :: Performing episode search for Black Mirror
23:11:32 INFO::MANUAL-253463 :: [Rarbg] :: 8 episode items in response from https://torrentapi.org/pubapi_v2.php?app_id=SickGear&mode=search&format=json_extended&category=18;41&limit=100&sort=last&ranked=0&token=6cqv9ih37l&search_imdb=tt2085059&search_string=S03E01&min_seeders=1
23:11:33 INFO::MANUAL-253463 :: [Rarbg] :: 4 episode candidates
23:11:33 INFO::MANUAL-253463 :: Quality is 1080p WEB-DL for Black.Mirror.S03E01.PROPER.1080p.WEBRip.X264-DEFLATE[rartv]
23:11:33 INFO::MANUAL-253463 :: Quality is 1080p WEB-DL for Black.Mirror.S03E01.1080p.WEBRip.x264-SKGTV[rartv]
23:11:33 INFO::MANUAL-253463 :: Quality is 720p WEB-DL for Black.Mirror.S03E01.PROPER.720p.WEBRip.X264-DEFLATE[rartv]
23:11:33 INFO::MANUAL-253463 :: Quality is 720p WEB-DL for Black.Mirror.S03E01.720p.WEBRip.x264-SKGTV[rartv]
23:11:33 INFO::MANUAL-253463 :: Downloading Black.Mirror.S03E01.PROPER.1080p.WEBRip.X264-DEFLATE[rartv] from Rarbg
23:11:40 WARNING::MANUAL-253463 :: Connection error HTTPConnectionPool(host='thetorrent.org', port=80): Max retries exceeded with url: /torrent/E7D7DC53BB19306983C2B3750CE402889D93944A.torrent (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f57c03374d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)) while loading URL http://thetorrent.org/torrent/E7D7DC53BB19306983C2B3750CE402889D93944A.torrent
23:11:40 ERROR::MANUAL-253463 :: All torrent cache servers failed to return a downloadable result
</pre>

**Comment by JackDandy** [comment]
Ok you guys need to avoid using those currently dead servers (which SG cannot do anything about).

In the search settings, set up SG to connect directly to your torrent client  - that is don't use blackhole method. This will send magnets directly to the torrent client and everything will work fine from there.
