### ISSUE TITLE
Not working with PiSexy

### ISSUE THREAD

**Issue by rbhamilton** [SickGear/SickGear#840]
PiSexy has made some changes and SickGear no longer works with it.  

Here's the log:

2016-12-08 13:41:01 RECENT-SEARCH :: [PiSexy] :: Failed to authenticate or parse a response from PiSexy, abort provider

**Comment by JackDandy** [comment]
#841

**Comment by JackDandy** [comment]
#841

Re: your notes... I can't recall but at the time of writing the PiS module (~2 years ago), there was no api.  Also, it doesn't provide the features that sg can handle.  Therefore, it doesn't (didn't) make sense to delete the time and care invested in the sg pis module to use something less equipped. When they make a change, simply come here and we will change to suit. Won't be often as they are pretty stable - which is why SickGear was the first to support them.

**Comment by rbhamilton** [comment]
So... It's fixed?  Or not fixed?  That answer wasn't very clear...

**Comment by JackDandy** [comment]
Erm, the #nnn link I sent an hour ago - that **is** the fix, I guess you didn't read the text in there.

**Comment by JackDandy** [comment]
Erm, the #nnn link I sent an hour ago **is** the fix, I guess you didn't read the text in there. Update your sg. Also, the big green "fixed" label on this thread, lol ? I recommend you use github properly instead of email - i dont know whwy they use such a thing - people always fail with it.

**Comment by rbhamilton** [comment]
OK. Did the update. Thanks!
