### ISSUE TITLE
Feature request -Size limits

### ISSUE THREAD

**Issue by PearcutEagle** [SickGear/SickGear#961]
Hi, I recently migrated from sickrage to your fork but there is a feature I couldn't find that I am really missing. I would like to set size restrictions per quality. 

In the end it is really frustrating to have 2gb 720p episodes download or 300mb 1080p episodes. It does very little for the quality.

Thanks!

**Comment by JackDandy** [comment]
Hi @PearcutEagle

You mention a 720p 2Gb file, and a 300Mb 1080p file, but are you speaking in the hypothetical?  Because we are yet to prove that the case your raise actually exists, if it does exist, then that is something SG would look at closer, however, speculation to an event that has never occurred with the SG search and filtration system is not one that merits this troublesome option, let me explain...

Using a size limit window to determine a positive result actually creates more false results than what the idea of it is supposed to resolve.  For example, filesizes vary tremendously across qualities, with bit rates, with compression (x264 v x265), and also where a release may randomly be a 2 part episode that is 90 mins instead of 45 mins - these are a few reasons why size limit matching is such a terrible idea and why it was never implemented.

The feature you describe is actually a placebo that masks over an issue instead of dealing with it head on.  The real symptom is more often than not dealt with at the media provider or by using global search ignore words to pinpoint target the very rare release name. 

Thank you.

**Comment by PearcutEagle** [comment]
Hi @JackDandy, my example was a theoretical indeed, what I have seen though is 1080p episodes encoded in x264 web-dl occupying 2GB of space, now for me this is not ok since it is the same size as the movies I acquire only a 45min episode is less than half the time of that movie.

That said I would like your advise in how I can refine my search to aim for around 1GB per episode without using x265 as an advanced filter and without specifying a preferred size limit on the file sizes (per quality setting).

A poorer man's argument would be that other apps such as sickbeard, sickrage, couchpotato and sonarr all have a filter on size, so there the community must have clearly anticipated a use case. Now I do not want to go to other apps since I've come to appreciate the reliability of the software you provide (so far execution has been flawless).

Ultimately its up to you to decide if you think this feature is worth the effort or not, I can only do my best to convince you ;D

**Comment by JackDandy** [comment]
Hi @PearcutEagle 

Our "Grandfather", Sick-beard, does not have size-limit matching exactly for the same reasons I have outlined.  Carefully considered design decisions has led SG to produce great results in terms of execution, something people get after a while of use -- and this means that some features are deemed to add no value to, (or worse, degrade), the overall quality of user experience.

It is very normal and proper that Web-DL files can be up 5Gb per episode, so if you want to have "around 1GB per episode", then **do not** download high bit rate Web-DL quality.  However, I would be remiss not to point out that it is a complete error to compare specifically Web-DL (WEB sourced not HDTV) quality TV releases with movie release file sizes because Web-DL frame bit rates are lossless and high from source, whereas the movies you are talking of are re-encoded at a far reduced bit rate.  You may consider Web-DL closer to bluray in terms of bit rate quality.

Anyway, to filter on lower grades, edit a show, select Quality to download as "Custom" and in the left column, only select HD TV -- this will limit filtering to 720p x264. And like I said, add "Ignore words" to fine tune filter out any anomalies you come across. Also, at step 3 of adding a show, save a default for this quality choice.

**Comment by PearcutEagle** [comment]
Thanks for your feedback, I will try to refine my searches with the given filtering settings see if I can get results more to my liking. 

Keep up the great work!
