### ISSUE TITLE
qBittorrent: Unable to send Torrent: Return code undefined (already exists in client?)

### ISSUE THREAD

**Issue by crazychrisnz** [SickGear/SickGear#979]
When doing backlog or new episodes, SickGear loads the episode into qBittorrent but does not flag as snatched/downloaded. Later it will try and re-snatch and fail with: `qBittorrent: Unable to send Torrent: Return code undefined (already exists in client?)`

What can (and does) happen also is that multiple versions/releases of the episode are snatched until the episode is **manually** changed from wanted to skipped in the gui. New (and wanted) episodes will remain permanently in wanted state and constantly loading new versions or throwing errors until they are manually changed to skipped.

This has been happening for some time, maybe since 0.12.20 but not confirmed as unsure when each product was updated on my system.  Have done full reinstalls of both products to no avail.

qBittorrent: v3.3.15 (Windows)

SickGear: Release 0.12.27
BRANCH: master / COMMIT: 8166cd96865f526c029fdb24e723665205ba32e4

**Comment by JackDandy** [comment]
I have just tested and there is no issue here - Win10 x64, Python 2.7.13, qB 3.3.15, with SG 0.12.27 on Master. SickGear snatches, sends to qB, sets the item as snatched in the ui, and I see the item in qB in progress.

Therefore, I can only assume your Config/Search Settings/Torrent Results for qB may not be set up correctly, try doing a `Test connection` to make sure of that part.

**Comment by crazychrisnz** [comment]
Update: downgraded to qB 3.3.11 and now things are working fine.

**Comment by DogSledder** [comment]
I've got the same problem. Seems to only appear on the sites I use that provide only magnet links. The site I use that provides actual Torrent files works ok.

It's been this way for a while now.

qBittorrent: v3.3.16 (64 bit - Windows 7)
SickGear: BRANCH: master / COMMIT: 1bdab584c43bd0da297d1fbd6351edf9849779ed

**Comment by JackDandy** [comment]
@DogSledder 

Please supply name of Media Provider, name of Show, Season and Episode thats fails .

Thanks.

**Comment by JackDandy** [comment]
[Fixed 0.12.36](https://github.com/SickGear/SickGear/releases/tag/release_0.12.36)

**Comment by sledgehammer999** [comment]
The problem is 2-fold:
1. We don't have a dedicated member to keep the wiki updated. Since we're all volunteers I can't put the responsibly to someone specific. Personally, I am not really involved with the WebUI stuff. As a **suggestion** I ask if @Chocobo1 wants to maintain such a list in the wiki.
2. You should really check the [API number](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#get-api-version) and [minimum supported API number](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#get-minimum-api-version) in your app before continuing with calling other APIs. API number changes every time we add, delete or modify the API. API_min increases everytime we delete an existing API call or modify an existing one in a backwards incompatible way.

**Comment by JackDandy** [comment]
@sledgehammer999 

Yeah, maintaining a list of changes requires extra vigilance, but projects of even one lead manage to keep an API for developers in such a way that doesn't break stuff overnight.

Let's focus on returning a value from a method... an API should **never** fundamentally change such that a break occurs to 3rd party apps (unless a critical security issue), instead, amendments or new endpoints can be done - think of the carnage if theTvdb, Trakt, uTorrent etc. did such things. Of course qB is smaller - but base principles can still apply, surely.  In this particular case, the 'Ok.' and 'Fail.' change should never have been accepted for merged, instead, a new function could of been created called something like, "GetLastError()" which could have returned what the original submitter was trying to achieve far more elegantly, and without blowing up all the applications that trust in what qB will return as being consistent.  

Finally, your proposal to lock the user to a qB/API version of your app because - the API can change at anytime is not optimal for the general community at large who develop and support qB - remember, our resources are also limited.  So in conclusion, qB could be "nicer" by design to projects that use its API. I hope you take what i've said in the spirit it is intended, I like, use, and often recommend qB to others.

**Comment by Chocobo1** [comment]
> it has to be said that this is the second time this year that qB has broken apps due to no systems in place for a smooth API change, please look into making transitions more stable friendly :)

Would it help if qbt start using Semantic Versioning for api version?
If yes, pls voice your opinion in this thread: https://github.com/qbittorrent/qBittorrent/pull/7610#discussion_r145817209

>As a suggestion I ask if @Chocobo1 wants to maintain such a list in the wiki.

Sorry, my hands are full and isn't that exactly a change log / git log?
https://github.com/qbittorrent/qBittorrent/commits/master/src/webui/webapplication.cpp

**Comment by sledgehammer999** [comment]
>your proposal to lock the user to a qB/API version of your app because - the API can change at anytime is not optimal for the general community at large who develop and support qB - remember, our resources are also limited.

Just a clarification: The min_API may stay the same for several qbt versions.
